Repository neomutt/neomutt, pull requests merged in 2018-06, with the labels that each got.

#1246 Update ja translation
  po/ja.po
Labels: status:ready

#1254 fix trash mailbox
  mx.c
Labels: bug:regression, status:ready, type:bug

#1256 fcc_attach: Don't ask every time
  send.c
Labels: status:in-progress

#1233 Refactor resize.c into separate functions.
  resize.c
Labels: status:in-progress

#1263 Fix env var quoting in backticks
  init.c
  mutt.h
Labels: bug:regression, status:in-progress, type:bug

#1260 Fixes in style
  bcache.c
  mutt/address.c
  mutt_notmuch.c
  url.h
Labels: status:in-progress

#1268 Put bit fields together
  browser.h
  hcache/hcache.c
  mutt/address.h
  mutt_menu.h
Labels: status:in-progress
