Repository neomutt/neomutt, pull requests merged in 2018-03, with the labels that each got.

#1083 Fix usage of mutt_progress_init after b310689
  nntp.c
Labels: status:ready, type:bug

#1079 notmuch: stop if db open fails
  mutt_notmuch.c
Labels: status:ready, topic:notmuch, type:bug

#1089 Fallback to C.UTF-8 if en_US.UTF-8 cannot be set
  test/rfc2047.c
Labels: status:ready, topic:testing

#1091 Make sure git_ver.h doesn't eat random 'g's out of tag names
  Makefile.autosetup
Labels: status:ready, topic:build-process, type:bug

#1080 Make sure paths created by header/body/news cache are POSIX-compliant
  bcache.c
  hcache/hcache.c
  muttlib.c
  newsrc.c
Labels: status:ready, type:enhancement

#1097 lua: fix crash when setting a string
  init.c
Labels: bug:crash, status:ready, type:bug

#1098 Expose EXTRA_CFLAGS_FOR_BUILD and EXTRA_LDFLAGS_FOR_BUILD
  Makefile.autosetup
  auto.def
  doc/Makefile.autosetup
Labels: status:ready, topic:autosetup, topic:build-process

#1102 Update Turkish translation
  po/tr.po
Labels: status:in-progress

#1101 Support —with-sysroot configure arg
  Makefile.autosetup
  auto.def
Labels: status:ready, topic:autosetup, topic:build-process

#1103 Tidy space-before-tabs and multiple spaces
  doc/Makefile.autosetup
  po/Makefile.autosetup
Labels: status:in-progress

#1113 fix return code for 'neomutt -Z'
  main.c
Labels: bug:regression, status:ready, type:bug

#1110 fix Notmuch deprecation warning
  auto.def
  mutt_notmuch.c
Labels: status:in-progress, topic:build-process, topic:notmuch

#1115 refactor: move the envlist code to the library
  Makefile.autosetup
  conn/tunnel.c
  filter.c
  init.c
  main.c
  mutt/envlist.c
  mutt/envlist.h
  mutt/mutt.h
  protos.h
  sendlib.c
  system.c
Labels: status:ready, topic:refactoring, type:enhancement

#1116 refactor: startup hostname
  init.c
Labels: status:ready, topic:refactoring, type:enhancement
