Repository neomutt/neomutt, pull requests merged in 2018-11, with the labels that each got.

#1385 format: use description by default
  init.h
Labels: status:in-progress

#1395 imap: fixup error handling of imap_conn_find2
  imap/imap.c
Labels: status:in-progress

#1394 imap: add missing free_edata pointer
  imap/message.c
Labels: status:in-progress

#1392 browser: search on description if it exists
  browser.c
Labels: status:in-progress

#1393 mxapi: mx_path_canon should not double / uri
  mx.c
Labels: status:in-progress

#1398 flags: change confusing var name
  flags.c
Labels: status:in-progress

#1399 move Context.new
  flags.c
  mailbox.c
  mailbox.h
  mbox/mbox.c
  mx.c
  nntp/nntp.c
Labels: status:in-progress

#1397 Remove unused ImapAccountData->account
  imap/imap_private.h
Labels: status:in-progress

#1401 imap: when opening mailbox, reset Mailbox attrs
  imap/imap.c
Labels: status:in-progress

#1403 remove mailbox.closing
  imap/command.c
  imap/imap.c
  imap/imap.h
  imap/imap_private.h
  mailbox.h
  mx.c
Labels: status:in-progress

#1408 Also delete account if needed during unmailboxes
  account.c
  account.h
  mailbox.c
  mx.c
  mx.h
Labels: status:in-progress

#1409 Simplify account cleanup
  account.c
  account.h
Labels: status:in-progress

#1412 Devel/list find const
  mutt/list.c
  mutt/list.h
Labels: status:in-progress

#1411 Pull request for better-adata-handling
  imap/browse.c
  imap/imap.c
  imap/imap_private.h
  imap/util.c
Labels: status:in-progress

#1414 fix some msg_new update
  commands.c
  mx.c
Labels: status:in-progress

#1418 Do not create an additional ctx for syncing a mailbox
  imap/imap.c
Labels: bug:crash, status:in-progress

#1424 imap: ensure we can't delete the current selected mailbox
  browser.c
Labels: status:in-progress

#1426 imap: move some ImapAccountData attributes to ImapMboxData
  imap/command.c
  imap/imap.c
  imap/imap_private.h
  imap/message.c
  imap/util.c
Labels: status:in-progress

#1431 imap: tidy doc
  imap/imap.c
  imap/imap_private.h
  imap/util.c
Labels: status:in-progress

#1441 ssl: don't shutdown broken connection
  conn/ssl.c
Labels: status:in-progress

#1434 imap: reduce complexity of imap_exec
  imap/auth_login.c
  imap/auth_oauth.c
  imap/command.c
  imap/imap.c
  imap/imap_private.h
  imap/message.c
Labels: status:in-progress

#1442 Keep adata on imap-logout-all
  imap/imap.c
  imap/imap_private.h
Labels: bug:crash, status:in-progress

#1443 imap: remove unused define
  imap/imap_private.h
Labels: status:in-progress

#1452 How to run shell commands in global-hooks
  doc/manual.xml.head
Labels: status:in-progress

#1454 Change instances of GMail to Gmail for consistency
  doc/manual.xml.head
  doc/neomuttrc.man.head
Labels: status:in-progress

#1456 notmuch: don't overwrite nm_default_uri
  notmuch/nm_db.c
Labels: status:in-progress, topic:notmuch

#1458 fix crash in eat_date()
  pattern.c
Labels: status:in-progress

#1451 Change dependency chain regarding git_ver
  .gitignore
  Makefile.autosetup
  globals.h
Labels: status:in-progress, topic:build-process

#1461 imap: handle case where adata->mailbox is NULL
  imap/command.c
Labels: status:in-progress

#1446 postpone: Don't reopen Postponed context
  postpone.c
Labels: status:ready

#1459 postpone: fix Postcount when we are in current selected mailbox
  postpone.c
  protos.h
  send.c
  status.c
Labels: status:ready

#1463 Fix unsub from the selected mailbox by just hiding it
  mailbox.c
Labels: bug:crash, status:ready

#1467 imap: login on startup
  imap/imap.c
Labels: status:in-progress
