Repository neomutt/neomutt, pull requests merged in 2018-10, with the labels that each got.

#1351 build: make samples reflect the provided libexecdir in ./configure
  contrib/Makefile.autosetup
  doc/Makefile.autosetup
Labels: status:in-progress

#1323 Notmuch: Change default window to be open ended
  notmuch/mutt_notmuch.c
Labels: status:in-progress, topic:notmuch

#1346 notmuch: reconstruct thread on-the-fly upon <entire-thread> w/o vfolder
  curs_main.c
Labels: status:discuss, status:in-progress, topic:notmuch, type:enhancement

#1241 notmuch: use global settings for vfolder-from-query
  curs_main.c
  notmuch/mutt_notmuch.c
Labels: status:in-progress, topic:notmuch, type:bug

#1355 notmuch: count messages in queried threads
  notmuch/mutt_notmuch.c
Labels: status:in-progress, topic:notmuch

#1363 manual: document `named-mailboxes` for neomuttrc
  doc/neomuttrc.man.head
Labels: status:in-progress

#1365 Try adding status indicator R for my address in Reply-To
  doc/manual.xml.head
  hdrline.c
  init.h
Labels: status:in-progress

#1370 Do not use disconnected socket.
  imap/imap.c
Labels: status:in-progress

#1372 Devel/attachments
  globals.h
  main.c
  mutt_attach.c
  mutt_attach.h
Labels: status:in-progress

#1377 notmuch: duplicate `uri` during sync
  notmuch/mutt_notmuch.c
Labels: status:in-progress

#1376 notmuch: use existing open database if possible
  notmuch/nm_db.c
Labels: status:in-progress, topic:notmuch

#1379 notmuch: rework progress update math
  notmuch/mutt_notmuch.c
Labels: status:in-progress, topic:notmuch

#1382 notmuch: fixed vfolder-from-query
  notmuch/mutt_notmuch.c
Labels: status:in-progress
