Repository neomutt/neomutt, pull requests merged in 2018-04, with the labels that each got.

#1129 Generate .clang_complete
  .clang_complete.in
  .gitignore
  Makefile.autosetup
  auto.def
Labels: status:ready, topic:autosetup

#1132 Remove reminiscent of txt2c
  .gitignore
Labels: status:in-progress

#1137 Let mutt_ch_choose report conversion failure
  handler.c
  imap/utf7.c
  mutt/charset.c
  mutt/charset.h
  mutt/idna.c
  mutt/rfc2047.c
Labels: bug:confirmed, bug:crash, status:ready

#1138 Clarify the relation between NeoMutt and Mutt
  README.md
Labels: status:in-progress

#1134 minor IMAP string handling fixes
  bcache.c
  mutt/string.c
  mutt/string2.h
Labels: status:in-progress

#1142 init.c: Ensure more consistent variable dumps
  init.c
Labels: status:in-progress

#1158 init.c: convert MyVars to use TAILQ
  init.c
Labels: status:in-progress

#1159 mutt/logging.c: set line buffering for logging stream
  mutt/logging.c
Labels: status:discuss, status:in-progress

#1157 mutt/file.c: split mutt_file_{lock,unlock} into flock/fcntl versions
  AUTOSETUP.md
  INSTALL
  auto.def
  mutt/file.c
Labels: status:in-progress

#1163 Respect environment VISUAL and EDITOR variables
  init.c
Labels: status:in-progress

#1164 Avoid trailing white space on header lines with no value
  sendlib.c
Labels: status:ready

#1170 Improve the usage() string
  doc/manual.xml.head
  doc/neomutt.man
  main.c
Labels: status:in-progress, topic:refactoring, type:enhancement
