Repository neomutt/neomutt, pull requests merged in 2018-05, with the labels that each got.

#1130 message.c: retry message parse if first attempt is zero-length
  imap/message.c
Labels: status:in-progress

#1167 Do not stop trying to log into an IMAP server at the first NO
  imap/auth.c
Labels: bug:confirmed, status:in-progress

#1190 Accept whitespace in RFC2047 encoded-text productions
  mutt/rfc2047.c
  test/rfc2047.c
Labels: bug:confirmed, bug:regression, status:ready

#1191 Update zh_CN translation
  po/zh_CN.po
Labels: status:ready

#1196 Update zh_CN translation
  po/zh_CN.po
Labels: status:in-progress

#1199 Update zh_CN translation
  po/zh_CN.po
Labels: status:ready

#1200 Update zh_CN translation
  po/zh_CN.po
Labels: status:ready

#1202 remove useless question of PR template; add passing tests to acceptance criteria.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status:ready

#1204 sync with doc tidying in 77155bb
  doc/Makefile.autosetup
Labels: status:in-progress

#1205 Update zh_CN translation
  po/zh_CN.po
Labels: status:in-progress

#1135 Expand variables inside backticks
  init.c
  mutt.h
Labels: status:in-progress, type:enhancement

#1176 Partial solution to #1165
  attach.c
  editmsg.c
  mutt/file.c
  mutt/file.h
Labels: status:in-progress

#1210 build: stop on install failure
  Makefile.autosetup
  contrib/Makefile.autosetup
  doc/Makefile.autosetup
  po/Makefile.autosetup
Labels: status:in-progress, topic:build-process, type:bug

#1174 Convert Aliases to use TAILQ
  addrbook.c
  alias.c
  alias.h
  globals.h
  init.c
  protos.h
Labels: good first issue, help wanted, mentor, status:in-progress

#1220 Do not truncate shell commands in backticks on the first ; or #
  init.c
Labels: status:in-progress

#1212 Honour SASL-IR IMAP capability in SASL PLAIN
  conn/sasl_plain.c
  imap/auth_plain.c
Labels: bug:confirmed, status:ready

#1227 Update zh_CN translation
  po/zh_CN.po
Labels: status:in-progress

#1232 Move LSUB call from connection establishment to mailbox SELECTion
  imap/imap.c
  init.h
Labels: status:ready, type:enhancement

#1234 Don't let info messages reset error messages' timeouts
  curs_main.c
Labels: bug:confirmed, status:ready

#1139 Add the mutt_ch_check API
  mutt/charset.c
  mutt/charset.h
Labels: status:in-progress

#1237 Handle a BAD response in AUTH PLAIN w/o initial response
  imap/auth_plain.c
Labels: bug:confirmed, status:ready

#797 pager: index must be rebuild when check mailbox returns MUTT_REOPENED
  pager.c
Labels: status:ready

#1239 Remove pgpsignature
  Makefile.autosetup
  contrib/Makefile.autosetup
  contrib/pgp2.rc
  contrib/pgp5.rc
  contrib/pgp6.rc
  ncrypt/pgplib.c
  ncrypt/pgplib.h
  pgppubring.c
Labels: status:in-progress

#1240 Update ja translation
  po/ja.po
Labels: status:in-progress
