Repository neomutt/neomutt, pull requests merged in 2018-02, with the labels that each got.

#1055 Fix out-of-bounds read in mutt_str_lws_len
  mutt/string.c
Labels: status:ready, type:bug

#1056 fix crash when decoding parameters
  rfc2231.c
Labels: bug:crash, status:in-progress

#1058 Ncurses always has resizeterm, remove unnecessary ifdefs
  Makefile.autosetup
  auto.def
  curs_lib.c
  curs_main.c
  enter.c
  menu.c
  mutt/signal.c
  mutt_signal.c
  pager.c
  resize.c
  signal.c
  version.c
Labels: status:ready, type:enhancement

#1062 fix regexes using '!' (not)
  init.c
Labels: bug:regression, status:ready, type:bug

#1064 Allow choosing a particular version of BerkeleyDB via --with-bdb-version
  auto.def
Labels: status:ready, type:enhancement

#1068 fix: missing ! when checking regex pointer
  mutt/regex.c
Labels: status:in-progress

#1077 Update to latest autosetup
  autosetup/system.tcl
Labels: status:ready

#1078 Move address to libmutt and merge it with mutt_address
  Makefile.autosetup
  addrbook.c
  alias.c
  commands.c
  compose.c
  copy.c
  edit.c
  envelope.c
  group.c
  hcache/hcache.c
  hdrline.c
  hook.c
  init.c
  main.c
  mbox.c
  mutt/address.c
  mutt/address.h
  mutt/mutt.h
  mutt_address.c
  mutt_lua.c
  muttlib.c
  mx.c
  ncrypt/crypt.c
  ncrypt/crypt_gpgme.c
  ncrypt/pgp.c
  ncrypt/pgpinvoke.c
  ncrypt/pgpkey.c
  ncrypt/smime.c
  parse.c
  pattern.c
  pop_auth.c
  query.c
  recvcmd.c
  remailer.c
  rfc2047.c
  send.c
  sendlib.c
  smtp.c
  sort.c
  url.c
Labels: status:ready, topic:refactoring

#1084 Clarify precedence of settings in config files.
  doc/manual.xml.head
Labels: status:in-progress
