Repository neomutt/neomutt, pull requests merged in 2019-06, with the labels that each got.

#1731 devel: show backtrace on segfault
  Makefile.autosetup
  auto.def
  backtrace.c
  mutt.h
  mutt/signal.c
  mutt/signal2.h
  mutt_signal.c
  test/signal/mutt_sig_init.c
Labels: status:discuss, topic:testing, type:enhancement

#1737 Fix segfault on bounce
  smtp.c
Labels: bug:confirmed, bug:crash, bug:regression

#1732 Update to latest autosetup, use @include feature
  Makefile.autosetup
  auto.def
  autosetup/cc.tcl
  autosetup/system.tcl
  doc/Makefile.autosetup
  po/Makefile.autosetup
Labels: topic:build-process

#1733 Save attachments without prompting.
  init.h
  recvattach.c
  recvattach.h
Labels: status:discuss, status:in-progress, type:enhancement

#1753 Clarify header_cache behaviour on missing paths
  init.h
Labels: docs:manual

#1738 Optionally use pkg-config for 3rd party dependencies
  auto.def
Labels: status:ready, topic:build-process

#1757 build: check which idn2 headers to include
  auto.def
Labels: topic:build-process

#1759 Avoid UB when clearing stdin
  curs_lib.c
Labels: topic:refactoring, topic:stability
