Repository neomutt/neomutt, pull requests merged in 2019-09, with the labels that each got.

#1822 Tidy the progress API
  globals.h
  imap/message.c
  index.c
  maildir/shared.c
  mbox/mbox.c
  nntp/nntp.c
  notmuch/mutt_notmuch.c
  pattern.c
  pop/pop.c
  pop/pop_lib.c
  progress.c
  progress.h
  smtp.c
  test/pattern/dummy.c
Labels: status:ready, type:enhancement

#1848 Add mutt_date_epoch() API, use it instead of time()
  autocrypt/autocrypt.c
  browser.c
  conn/ssl_gnutls.c
  email/parse.c
  handler.c
  hdrline.c
  imap/command.c
  imap/imap.c
  imap/util.c
  init.c
  maildir/maildir.c
  maildir/shared.c
  mutt/date.c
  mutt/date.h
  mutt/file.c
  mutt/logging.c
  mutt_mailbox.c
  mx.c
  ncrypt/pgp.c
  ncrypt/smime.c
  nntp/nntp.c
  notmuch/mutt_notmuch.c
  pop/pop.c
  progress.c
  send.c
  sendlib.c
  test/date/mutt_date_add_timeout.c
Labels: type:enhancement

#1852 fix: mutt_any_key_to_continue()
  curs_lib.c
Labels: type:bug

#1851 Recurse into subparts when counting attachments
  globals.h
  init.c
  mutt.h
  mutt_parse.c
  mutt_parse.h
Labels: status:ready, type:enhancement
