Repository neomutt/neomutt, pull requests merged in 2019-01, with the labels that each got.

#1514 imap: command: Adds unique sequence IDs
  imap/command.c
  imap/imap_private.h
  imap/util.c
Labels: status:in-progress

#1517 solarized dark color scheme: Remove outdated comment about ncurses
  contrib/colorschemes/solarized-dark-256.neomuttrc
Labels: status:in-progress

#1519 notmuch: make sure nm_db_longrun_done() release DB
  notmuch/nm_db.c
Labels: status:in-progress

#1518 fix: mutt/charset.c: only include libintl.h if ENABLE_NLS is defined
  mutt/charset.c
Labels: status:in-progress

#1521 folder-hook: try matching on description
  hook.c
  hook.h
  index.c
  main.c
  sendlib.c
Labels: status:in-progress

#1506 Command prompt should close when deleting the ':' as it does in vim
  enter.c
Labels: status:in-progress

#1528 Don't override ndata with temporary context
  mx.c
Labels: status:in-progress

#1531 Relax non-empty requirement on compose_format, pager_format, and status_format
  init.h
Labels: status:in-progress

#1534 +install instructions in README.md
  README.md
Labels: status:in-progress

#1533 notmuch: implement read-only vfolder-from-query
  doc/manual.xml.head
  functions.h
  index.c
  opcodes.h
Labels: status:in-progress

#1538 Allow the creation of a new mbox when saving to a local file
  mx.c
Labels: bug:confirmed, status:in-progress

#1541 tags: fix multiple tags set on multiple emails
  email/tags.c
  imap/imap.c
Labels: status:ready
