Repository neomutt/neomutt, pull requests merged in 2019-11, with the labels that each got.

#1915 fix mbox save-to-trash
  mbox/mbox.c
Labels: type:bug

#1914 lmdb: fix txn leak
  hcache/lmdb.c
Labels: type:bug

#1919 Escape space to show second level folders with spaces
  doc/manual.xml.head
Labels: docs:manual

#1936 notmuch: use nm_default_uri if no mailbox data
  notmuch/nm_db.c
Labels: topic:notmuch

#1951 fix: trash to non-existent file/dir
  maildir/maildir.c
  mx.c
Labels: type:bug

#1959 fix build/tests for 32-bit arches
  email/parse.c
  mutt/date.c
  mutt/date.h
  test/date/mutt_date_gmtime.c
  test/string/mutt_str_atol.c
  test/string/mutt_str_atoui.c
  test/string/mutt_str_atoul.c
  test/string/mutt_str_atoull.c
Labels: type:bug

#1963 fix new-mail flags and behaviour
  mbox/mbox.c
  mutt_mailbox.c
  mx.c
Labels: type:bug

#1977 mutt_save_message_ctx requires the mailbox to be in append mode
  imap/imap.c
Labels: bug:confirmed

#1974 Revert the gui refactoring relating to clearing the screen.
  curs_lib.c
  enter.c
  index.c
  menu.c
  mutt_window.c
  mutt_window.h
  pager.c
Labels: type:bug

#1981 Do not check hidden mailboxes for new mail
  mutt_mailbox.c
Labels: bug:confirmed

#1980 Fix new_mail_command notifications
  index.c
Labels: bug:confirmed

#1991 Fix crash in tunnel's conn_close
  conn/tunnel.c
Labels: bug:crash

#1999 fix fcc for deep dirs
  maildir/maildir.c
  mbox/mbox.c
  sendlib.c
Labels: bug:crash

#1998 imap: fix crash when new mail arrives
  imap/imap.c
Labels: bug:crash, topic:imap

#2005 quieten messages on exit
  main.c
Labels: type:bug

#1997 fix: crash after failed mbox_check
  context.c
  index.c
  mbox/mbox.c
  mx.c
  pager.c
Labels: bug:crash
