Repository neomutt/neomutt, pull requests merged in 2019-03, with the labels that each got.

#1580 Fix mutt_pipe_message() and mutt_print_message()
  commands.h
  index.c
  pager.c
Labels: status:in-progress

#1585 Ifdef envvars
  doc/manual.xml.head
  init.c
Labels: status:in-progress

#1593 Disable all history operations if history is not enabled
  mutt/history.c
Labels: bug:confirmed, bug:crash, status:in-progress

#1598 mx: fix mbox double free
  context.c
  mx.c
Labels: bug:crash, status:ready, type:bug

#1601 Encapsulate gmtime() and localtime()
  browser.c
  hdrline.c
  mutt/date.c
  mutt/date.h
  mutt/logging.c
  ncrypt/crypt.c
  ncrypt/crypt_gpgme.c
  ncrypt/pgpkey.c
  nntp/nntp.c
  pattern.c
  sendlib.c
Labels: status:in-progress

#1604 po/zh_CN: complete translation
  po/zh_CN.po
Labels: status:in-progress

#1602 Make NotMuch hcache-aware
  globals.h
  imap/imap.c
  imap/imap_private.h
  imap/message.c
  imap/util.c
  maildir/lib.h
  maildir/maildir.c
  maildir/shared.c
  mx.h
  nntp/newsrc.c
  nntp/nntp.c
  nntp/nntp_private.h
  notmuch/mutt_notmuch.c
  pop/pop.c
Labels: status:ready, topic:notmuch, type:enhancement

#1526 pattern: change Pattern linked-list(s) to use queue.h SLIST_* macros
  context.h
  hook.c
  imap/imap.c
  imap/imap.h
  index.c
  menu.c
  mutt_curses.h
  pattern.c
  pattern.h
  score.c
Labels: status:in-progress

#1611 lua: fix command-line processing
  mutt_lua.c
Labels: topic:lua-scripting, type:bug

#1615 fix further crash in ci_send_message()
  send.c
Labels: bug:crash

#1543 tags: Use STAILQ instead of strsep
  email/tags.c
  mutt/string.c
  mutt/string2.h
  test/main.c
  test/string.c
Labels: status:in-progress

#1614 Fix bogus mailbox size accounting
  context.c
  imap/message.c
  mailbox.c
  mailbox.h
  maildir/shared.c
  notmuch/mutt_notmuch.c
Labels: bug:confirmed, status:ready
