Repository neomutt/neomutt, pull requests merged in 2019-04, with the labels that each got.

#1631 Disable mailbox notify on close
  mx.c
Labels: bug:confirmed, bug:crash

#1634 curses: clear screen on exit
  main.c
Labels: type:bug

#1656 split Address into a separate library
  Makefile.autosetup
  addrbook.c
  address/address.c
  address/address.h
  address/group.c
  address/group.h
  address/idna.c
  address/idna2.h
  address/lib.h
  alias.c
  commands.c
  compose.c
  config/address.c
  conn/conn_raw.c
  conn/ssl.c
  copy.c
  edit.c
  email/envelope.c
  email/lib.h
  email/parse.c
  email/rfc2047.c
  hcache/serialize.c
  hdrline.c
  hook.c
  init.c
  init.h
  main.c
  mbox/mbox.c
  muttlib.c
  mx.c
  ncrypt/crypt.c
  ncrypt/crypt_gpgme.c
  ncrypt/pgp.c
  ncrypt/pgpinvoke.c
  ncrypt/pgpkey.c
  ncrypt/smime.c
  pattern.c
  pop/pop_auth.c
  query.c
  recvcmd.c
  remailer.c
  send.c
  sendlib.c
  smtp.c
  sort.c
  test/address.c
  test/config/address.c
  version.c
Labels: topic:refactoring

#1657 Make buffer pool initialization lazy
  init.c
  mutt/buffer.c
  mutt/buffer.h
Labels: type:bug

#1658 Support group-chat-reply in the index
  index.c
Labels: type:enhancement

#1661 Demote more 'first' and 'last' errors to messages
  menu.c
Labels: type:enhancement

#1664 imap: fix oauth
  imap/auth_oauth.c
Labels: topic:imap, type:bug

#1670 docs: add note about line continuation
  doc/manual.xml.head
Labels: docs:manual

#1676 Fix getting back to index after saving an edited message
  editmsg.c
Labels: bug:crash

#1681 Do not rely on idn2 to provide the compat layer to idna
  address/idna.c
  auto.def
Labels: topic:build-process

#1684 Fix nullptr dereference
  browser.c
Labels: bug:confirmed, bug:crash

#1685 Respect collapse_all after limit
  index.c
Labels: type:enhancement
