Repository neomutt/neomutt, pull requests merged in 2019-02, with the labels that each got.

#1552 browser: sort_browser attribute being modified after sorting browser
  browser.c
Labels: status:in-progress

#1560 Start to refactor mutt_index_menu()
  index.c
Labels: status:in-progress, topic:design, topic:refactoring

#1563 Refactor/tidy mutt_pager()
  pager.c
Labels: status:in-progress, topic:refactoring

#1566 Refactor/tidy mutt_select_file()
  browser.c
Labels: status:in-progress, topic:refactoring

#1568 Refactor/tidy mutt_compose_menu()
  compose.c
Labels: status:in-progress, topic:refactoring

#1565 Refactor/tidy mutt_enter_string_full()
  enter.c
Labels: status:in-progress, topic:refactoring

#1564 boolify mutt_set_flag() and friends
  commands.c
  editmsg.c
  flags.c
  imap/message.c
  index.c
  mutt_thread.c
  mx.c
  nntp/newsrc.c
  nntp/nntp.c
  notmuch/mutt_notmuch.c
  pager.c
  pattern.c
  postpone.c
  protos.h
  recvcmd.c
Labels: status:in-progress, topic:refactoring

#1547 notmuch: delegate msg_open_new to maildir backend
  maildir/lib.h
  maildir/maildir.c
  notmuch/mutt_notmuch.c
Labels: status:in-progress

#1548 Implemented summary :bind/:macro commands
  icommands.c
  keymap.c
  keymap.h
Labels: status:in-progress

#1555 Rewording of "postpone" message to avoid a common confusion
  compose.c
  init.h
Labels: status:in-progress
