Repository neomutt/neomutt, pull requests merged in 2019-07, with the labels that each got.

#1763 Fix saving a msg to a non-existent mailbox
  commands.c
Labels: bug:confirmed

#1784 Fix browsing an IMAP backend
  imap/browse.c
Labels: bug:confirmed, bug:crash

#1780 Refactor regex with custom wrapper
  browser.c
  commands.c
  email/parse.c
  email/rfc2047.c
  hook.c
  imap/browse.c
  index.c
  mutt/charset.c
  mutt/path.c
  mutt/regex.c
  mutt/regex3.h
  muttlib.c
  ncrypt/pgp.c
  nntp/browse.c
  notmuch/mutt_notmuch.c
  pager.c
  send.c
  test/Makefile.autosetup
  test/main.c
  test/regex/mutt_regex_match.c
Labels: topic:design, topic:refactoring
