Repository neomutt/neomutt, pull requests merged in 2019-05, with the labels that each got.

#1692 Do not link in a new Account after a failed login
  init.c
  mx.c
Labels: bug:confirmed, bug:crash, type:bug

#1695 Avoid useless reallocations in IMAP utf8/utf7 conversion
  imap/utf7.c
Labels: type:enhancement

#1696 Fix utf7/utf8 conversion of mailbox names in LIST response
  imap/command.c
Labels: topic:imap, type:bug

#1698 Allow to disable IMAP's ENABLE extension to work-around broken servers
  imap/imap.c
  imap/imap.h
  init.h
Labels: status:discuss

#1712 Do not cache a compiled regex to avoid leaks
  email/rfc2047.c
Labels: bug:confirmed

#1718 Avoid redundant sort in entire-thread.
  index.c
Labels: topic:notmuch, type:enhancement

#1720 fix: stop CUR_EMAIL underflow in entire-thread
  index.c
Labels: topic:notmuch

#1723 make OP_HALF_{UP,DOWN} behave symmetric.
  pager.c
Labels: type:bug

#1725 Fix list-reply regression introduced when converting Address to TAILQ
  send.c
Labels: bug:confirmed, bug:crash, bug:regression

#1722 doc: add example to find all maildir mailboxes
  doc/manual.xml.head
Labels: docs:manual, status:discuss, type:enhancement
