Repository neomutt/neomutt, pull requests merged in 2019-10, with the labels that each got.

#1865 build: fix autosetup warning
  auto.def
Labels: topic:build-process

#1863 Let reply_to take precedence over C_ReplySelf
  send.c
Labels: type:enhancement

#1871 pop: refactor refno
  email/email.h
  pop/pop.c
  pop/pop_lib.c
  pop/pop_private.h
Labels: topic:refactoring

#1872 fix read-only mbox
  mbox/mbox.c
Labels: type:bug

#1878 fix: abort entire-thread if database lacks message
  index.c
Labels: topic:notmuch

#1892 fix: crash when using 'alias -group'
  address/group.c
Labels: bug:crash

#1889 fix: reset charset
  init.c
Labels: type:bug

#1891 config: drop wrapmargin
  contrib/sample.neomuttrc-tlr
  doc/neomutt.pwl
  init.h
Labels: type:bug

#1896 eliminate MuttIndexWindow from create_filter()
  browser.c
  commands.c
  filter.c
  mutt_attach.c
  mutt_attach.h
  recvattach.c
Labels: topic:refactoring

#1895 fix: crash on failed ssl negotiation
  conn/ssl.c
Labels: bug:crash

#1893 NULL Mailbox pointer if it's deleted
  index.c
Labels: bug:crash

#1905 Resolve symbolic links when saving a message
  muttlib.c
Labels: bug:confirmed

#1907 Avoid dangling pointer in Account's mailbox list
  core/account.c
  init.c
  main.c
  mx.c
Labels: bug:confirmed, bug:crash

#1912 hooks: add logging
  hook.c
Labels: topic:refactoring
