Repository neomutt/neomutt, pull requests merged in 2019-08, with the labels that each got.

#1810 Fix segfault in PGP key selection
  ncrypt/pgpkey.c
Labels: bug:confirmed, bug:crash

#1812 Fix segfault in bounce
  smtp.c
Labels: bug:confirmed, bug:crash

#1813 Prioritize my_hdr over default ones and keep track of unique headers
  sendlib.c
Labels: type:enhancement

#1814 fix: alias expansion in compose
  alias.c
Labels: type:bug

#1816 Remember last visited folder when browsing
  browser.c
Labels: bug:confirmed, bug:regression

#1820 Fix struct Progress ownership of its msg
  index.c
  maildir/shared.c
  mbox/mbox.c
  notmuch/mutt_notmuch.c
  progress.c
  progress.h
Labels: bug:confirmed, bug:crash

#1823 Add mutt_date_epoch_ms API, convert gettimeofdays to use the new API
  autocrypt/autocrypt.c
  conn/conn_raw.c
  hcache/hcache.c
  hcache/hcache.h
  hcache/hcachever.sh
  hcache/serialize.c
  hcache/serialize.h
  imap/util.c
  maildir/shared.c
  mutt/date.c
  mutt/date.h
  mutt_logging.c
  notmuch/nm_db.c
Labels: status:in-progress, type:enhancement
