Repository neomutt/neomutt, pull requests merged in 2019-12, with the labels that each got.

#2016 fix: crash resizing notmuch mailbox
  mx.c
  notmuch/mutt_notmuch.c
Labels: bug:crash, topic:notmuch

#2007 show notmuch library version
  auto.def
  version.c
Labels: status:discuss, type:enhancement

#2020 Avoid negative allocation
  enriched.c
Labels: bug:confirmed, bug:crash

#2022 compose: fix attach message
  compose.c
  mx.c
Labels: type:bug

#2037 Fix uncollapse_jump
  index.c
Labels: bug:confirmed

#2034 Only try to perform entire-thread on maildir/mh mailboxes
  index.c
Labels: bug:confirmed, bug:crash, topic:notmuch

#2039 Fix crash in pager
  pager.c
Labels: bug:crash

#2035 Try to infer the signing key from the From address
  ncrypt/crypt.c
  ncrypt/crypt_gpgme.c
  ncrypt/crypt_gpgme.h
  ncrypt/crypt_mod.h
  ncrypt/cryptglue.c
  ncrypt/cryptglue.h
  ncrypt/pgp.c
  ncrypt/pgp.h
  ncrypt/smime.c
  ncrypt/smime.h
Labels: type:enhancement

#2047 Do not recurse a non-threaded message
  mutt_thread.c
Labels: bug:crash

#2054 Fix 'old append' trick in trash_append
  mx.c
Labels: bug:confirmed
