Repository neomutt/neomutt, pull requests merged in 2020-03, with the labels that each got.

#2156 Fixes #2154 by replacing mutt_str_replace calls on C_SmimeEncryptWith
  ncrypt/smime.c
  postpone.c
Labels: bug:crash

#2160 Allow controlling the "abort on backspace" feature
  enter.c
  globals.h
  mutt_config.c
Labels: type:enhancement

#2162 add / tidy debug code
  Makefile.autosetup
  addrbook.c
  auto.def
  autocrypt/autocrypt_acct_menu.c
  browser.c
  compose.c
  conn/ssl.c
  conn/ssl_gnutls.c
  debug/graphviz.c
  debug/lib.h
  debug/notify.c
  debug/window.c
  gui/color.c
  gui/curs_lib.c
  gui/mutt_window.c
  gui/mutt_window.h
  index.c
  main.c
  mutt_history.c
  mutt_signal.c
  ncrypt/crypt_gpgme.c
  ncrypt/pgpkey.c
  ncrypt/smime.c
  postpone.c
  query.c
  recvattach.c
  remailer.c
  version.c
Labels: type:enhancement

#2167 Update Makefile.autosetup
  Makefile.autosetup
Labels: topic:build-process

#2166 libconn: refactor gui dependencies
  Makefile.autosetup
  conn/conn_globals.c
  conn/conn_globals.h
  conn/conn_private.h
  conn/connaccount.h
  conn/connection.h
  conn/gnutls.c
  conn/gui.c
  conn/lib.h
  conn/openssl.c
  conn/raw.c
  conn/sasl.c
  conn/sasl.h
  conn/socket.c
  conn/socket.h
  conn/ssl.h
  conn/tunnel.c
  mutt_menu.h
  po/POTFILES.in
  po/bg.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/et.po
  po/eu.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/hu.po
  po/id.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: topic:design, topic:refactoring

#2169 Enable Cirrus CI for FreeBSD
  .cirrus.yml
Labels: topic:build-process

#2172 bug: force C local for email date
  mx.c
Labels: type:bug

#2177 fix command line sending
  main.c
  mbox/mbox.c
  mutt/file.c
  send.c
  sendlib.c
Labels: type:bug

#2179 fix emptying trash
  mx.c
Labels: type:bug

#2178 quieten gpgme warning
  ncrypt/cryptglue.c
Labels: type:bug

#2184 Demystify NeoMutt
  browser.c
  command_parse.c
  commands.c
  compose.c
  compress/compress.c
  context.c
  copy.c
  core/account.c
  core/account.h
  core/mailbox.h
  core/neomutt.c
  core/neomutt.h
  debug/graphviz.c
  debug/notify.c
  debug/parse_test.c
  doc/manual.xml.head
  editmsg.c
  flags.c
  imap/imap.c
  imap/util.c
  index.c
  maildir/lib.h
  maildir/maildir.c
  maildir/mh.c
  maildir/shared.c
  main.c
  mbox/mbox.c
  monitor.c
  mutt_attach.c
  mutt_config.c
  mutt_mailbox.c
  muttlib.c
  mx.c
  mx.h
  nntp/newsrc.c
  nntp/nntp.c
  notmuch/mutt_notmuch.c
  notmuch/notmuch_private.h
  pager.c
  pattern.c
  pop/pop.c
  pop/pop_lib.c
  recvattach.c
  send.c
  sendlib.c
  sort.c
  status.c
  test/config/dump.c
Labels: status:discuss, topic:refactoring

#2183 lib: move zstrm to libconn
  Makefile.autosetup
  conn/lib.h
  conn/zstrm.c
  conn/zstrm.h
  imap/imap.c
Labels: topic:design, topic:refactoring

#2186 Fix order of messages when checking for GPGMe
  auto.def
Labels: topic:build-process

#2190 Resolve symlinks only when necessary
  commands.c
  mutt/file.c
  mutt/file.h
  muttlib.c
Labels: bug:confirmed, bug:regression

#2191 Allow to read more than 1024 characters
  gui/curs_lib.c
Labels: bug:confirmed

#2193 neomutt: don't segfault on missing mailfile when inserting into hcache
  notmuch/mutt_notmuch.c
Labels: topic:hcache, topic:notmuch, type:bug

#2195 fix: COLUMNS env var
  commands.c
Labels: type:bug

#2196 use mutt_file_fopen() on config variables
  history/history.c
Labels: bug:crash

#2200 Libcompress update
  compress/lib.h
  compress/lz4.c
  compress/zlib.c
  compress/zstd.c
  doc/manual.xml.head
  hcache/hcache.c
  hcache/lib.h
  mutt_config.c
Labels: topic:design, topic:refactoring

#2209 Handle variables inside backticks in sidebar_whitelist
  command_parse.c
Labels: bug:confirmed

#2210 fix mailboxes with tildes
  main.c
Labels: type:bug

#2207 Create libstore -- key/value databases
  Makefile.autosetup
  compress/compress_private.h
  compress/lib.h
  globals.h
  hcache/backend.h
  hcache/hcache.c
  hcache/lib.h
  hcache/tdb.c
  history/history.c
  history/lib.h
  init.c
  mutt_config.c
  po/POTFILES.in
  store/bdb.c
  store/gdbm.c
  store/kc.c
  store/lib.h
  store/lmdb.c
  store/qdbm.c
  store/store.c
  store/tc.c
  store/tdb.c
  version.c
Labels: status:discuss, topic:design, topic:hcache, topic:refactoring

#2214 index(entire-thread): update current email pointer
  index.c
Labels: topic:notmuch

#2217 Use a regex in url_check_scheme
  email/url.c
  mutt/mapping.c
  mutt/mapping.h
Labels: topic:refactoring
