Repository neomutt/neomutt, pull requests merged in 2020-01, with the labels that each got.

#2055 refactor: init.[ch]
  Makefile.autosetup
  command_parse.c
  command_parse.h
  doc/Makefile.autosetup
  init.c
  init.h
  mutt_commands.c
  mutt_commands.h
  mutt_config.c
  mutt_config.h
  mutt_lua.c
  mutt_parse.c
  mutt_parse.h
  muttlib.c
  muttlib.h
  po/POTFILES.in
Labels: status:discuss, topic:refactoring

#2073 ssl: drop RAND_status() checks
  conn/ssl.c
Labels: topic:refactoring

#2074 build: WIFEXITED is defined in sys/wait.h
  mutt_attach.c
Labels: topic:build-process

#2079 Fix IMAP flag comparison code
  imap/imap.c
Labels: bug:confirmed, bug:regression

#2078 refactor: move functions data into a source file
  Makefile.autosetup
  doc/Makefile.autosetup
  functions.c
  functions.h
  help.c
  icommands.c
  init.c
  keymap.h
  po/POTFILES.in
Labels: topic:refactoring

#2082 Fix $move for IMAP mailboxes
  mx.c
Labels: bug:confirmed, bug:regression, status:ready

#2088 maildir_mbox_check_stats should only update mailbox stats if requested
  maildir/maildir.c
Labels: type:bug

#2084 update_index() never gets called
  imap/imap.c
  maildir/shared.c
  mx.c
Labels: type:bug

#2090 maildir: Don't error on new mail
  mx.c
Labels: topic:maildir, type:bug

#2102 Make sure we use the correct timezone in tests
  test/date/mutt_date_localtime.c
  test/date/mutt_date_localtime_format.c
  test/date/mutt_date_make_imap.c
  test/date/mutt_date_make_time.c
Labels: topic:testing

#2095 config: move functions to avoid dependency problems
  config/dump.c
  config/dump.h
  config/subset.c
  config/subset.h
Labels: topic:design, topic:refactoring
