Repository neomutt/neomutt, pull requests merged in 2020-05, with the labels that each got.

#2307 Make sure buffers are initialized on error
  index.c
  sidebar.c
Labels: bug:confirmed

#2233 prex: convert is_from
  email/from.c
  mutt/date.c
  mutt/date.h
  mutt/prex.c
  mutt/prex.h
  test/Makefile.autosetup
  test/date/mutt_date_is_day_name.c
  test/from/is_from.c
  test/main.c
Labels: topic:refactoring, type:enhancement

#2322 Fix list-reply by correct parsing of List-Post headers
  email/parse.c
  test/url/url_check_scheme.c
Labels: bug:confirmed

#2298 imap: use the connection delimiter if provided
  imap/util.c
  mutt_config.c
Labels: status:discuss

#2317 Inform but don't fail on IMAP NO/BAD responses
  imap/command.c
Labels: bug:confirmed

#2319 Window notifications
  addrbook.c
  autocrypt/acct_menu.c
  browser.c
  compose.c
  conn/gui.c
  debug/notify.c
  gui/curs_lib.c
  gui/mutt_window.c
  gui/mutt_window.h
  gui/reflow.c
  index.c
  index.h
  main.c
  mutt/notify_type.h
  mutt_history.c
  ncrypt/crypt_gpgme.c
  ncrypt/pgpkey.c
  ncrypt/smime.c
  pager.c
  postpone.c
  query.c
  recvattach.c
  remailer.c
  resize.c
  sidebar.c
Labels: topic:design, topic:refactoring

#2327 tidy makefile
  Makefile.autosetup
Labels: topic:build-process, topic:refactoring

#2328 mh: fix creating new mailbox
  maildir/mh.c
Labels: topic:maildir, type:bug

#2329 mmdf: fix creating new mailbox
  mbox/mbox.c
Labels: type:bug

#2334 fix tagged message count
  context.c
Labels: type:bug

#2336 Partially undo #2317: inform AND fail
  imap/command.c
Labels: bug:confirmed

#2343 Address Book tweaks
  addrbook.c
  alias.c
  alias.h
  command_parse.c
  docs/manual.xml.head
  mutt_config.c
  po/bg.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/et.po
  po/eu.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/hu.po
  po/id.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: status:discuss, type:enhancement

#2345 Check size of long using LONG_MAX instead of __WORDSIZE
  test/string/mutt_str_atol.c
  test/string/mutt_str_atoui.c
  test/string/mutt_str_atoul.c
  test/test_common.h
Labels: topic:testing

#2351 Rename Quiet to Verbose
  compmbox/compress.c
  core/mailbox.h
  imap/imap.c
  imap/message.c
  index.c
  maildir/shared.c
  mbox/mbox.c
  mx.c
  nntp/nntp.c
  notmuch/mutt_notmuch.c
  pager.c
  pop/pop.c
  query.c
  sort.c
Labels: status:discuss, topic:refactoring

#2357 sidebar: fix path comparison
  sidebar.c
Labels: type:bug

#2359 Restore CRLF->LF conversion in base64 decoding for text/inline parts
  handler.c
Labels: bug:confirmed
