Repository neomutt/neomutt, pull requests merged in 2020-08, with the labels that each got.

#2564 Fix setting attributes with S-Lang
  gui/mutt_curses.c
Labels: bug:confirmed

#2566 imap: fix crash in cmd_parse_expunge()
  context.c
  imap/imap.c
  imap/lib.h
Labels: bug:crash, topic:imap

#2571 Use our own string APIs
  imap/util.c
Labels: bug:confirmed

#2558 refactor: notify
  alias/dlgalias.c
  compose.c
  gui/curs_lib.c
  gui/dialog.c
  gui/mutt_window.c
  helpbar/helpbar.c
  index.c
  main.c
  mutt/notify.c
  mutt/notify.h
  mutt/notify_type.h
  mutt/observer.h
  mx.c
  sidebar/sidebar.c
  test/config/account.c
  test/config/address.c
  test/config/bool.c
  test/config/enum.c
  test/config/initial.c
  test/config/long.c
  test/config/mbtable.c
  test/config/number.c
  test/config/path.c
  test/config/quad.c
  test/config/regex.c
  test/config/slist.c
  test/config/sort.c
  test/config/string.c
  test/config/synonym.c
  test/gui/visible.c
  test/notify/notify_observer_add.c
Labels: topic:refactoring, type:bug

#2578 Avoid creating mailboxes for failed subscribes
  imap/imap.c
Labels: bug:confirmed

#2577 Do not assume that the sidebar window is a sibling of the current window
  command_parse.c
Labels: bug:crash

#2584 notmuch: improve synchronization with neomutt
  notmuch/notmuch.c
Labels: topic:notmuch

#2591 fix: maildir flag generation
  maildir/maildir.c
Labels: topic:maildir, type:bug

#2609 Make sure edata is not used by a backend of a different type
  compmbox/compress.c
  imap/imap.c
  maildir/lib.h
  maildir/maildir.c
  maildir/mh.c
  mbox/mbox.c
  mx.c
  mx.h
Labels: bug:confirmed, bug:crash

#2605 `:setenv ENV_NAME?` now queries for `ENV_NAME` variable, like `:set`
  command_parse.c
Labels: type:enhancement

#2607 Live Sorting in Address Book
  alias/dlgalias.c
  alias/gui.c
  alias/gui.h
  functions.c
Labels: type:enhancement

#2574 Implement ARRAY API
  Makefile.autosetup
  alias/dlgalias.c
  alias/dlgquery.c
  alias/gui.c
  alias/gui.h
  browser.c
  browser.h
  copy.c
  imap/browse.c
  imap/command.c
  imap/imap.c
  imap/lib.h
  imap/message.c
  imap/msn.c
  imap/msn.h
  imap/private.h
  imap/util.c
  menu.c
  mutt_menu.h
  send/sendmail.c
  test/array/mutt_array_api.c
Labels: type:enhancement

#2613 Restore indentation for named mailboxes, lost in #2596
  sidebar/window.c
Labels: bug:confirmed
