Repository neomutt/neomutt, pull requests merged in 2020-02, with the labels that each got.

#2108 refactor: tidy Url usage
  bcache.c
  email/url.c
  email/url.h
  imap/command.c
  imap/imap.c
  imap/util.c
  mutt_socket.c
  nntp/newsrc.c
  nntp/nntp.c
  pop/pop.c
Labels: status:discuss, topic:refactoring

#2109 Unify unmailboxes and unvirtual-mailboxes commands
  command_parse.c
  mutt_commands.c
  mutt_commands.h
Labels: type:bug

#2129 Fix context reinitialization in gpgme decryption
  ncrypt/crypt_gpgme.c
Labels: type:bug

#2132 enable gpgme by default
  mutt_config.c
Labels: status:discuss, topic:config-file, topic:security

#2134 oauth: if 'login' name isn't available use 'user'
  conn/connaccount.c
Labels: topic:imap, type:bug

#2118 notmuch: change uri to url
  ChangeLog.md
  doc/manual.xml.head
  email/email_globals.h
  email/parse.c
  index.c
  mutt_config.c
  nntp/newsrc.c
  notmuch/lib.h
  notmuch/mutt_notmuch.c
  notmuch/nm_db.c
  notmuch/notmuch_private.h
  po/bg.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/et.po
  po/eu.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/hu.po
  po/id.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: topic:notmuch, topic:refactoring

#2136 fix path comparisons
  mx.c
Labels: topic:notmuch, type:bug

#2144 Fix build of mutt_signal
  mutt_signal.c
Labels: topic:build-process

#2143 abort if run without a terminal
  main.c
Labels: type:bug

#2120 Fix commands that don’t need to have a non-empty mailbox to be valid
  index.c
Labels: status:discuss, type:bug

#1922 Zstandard compression for hcache of: bdb, gdbm and lmdb ;)
  AUTHORS.md
  Makefile.autosetup
  auto.def
  doc/makedoc_defs.h
  doc/manual.xml.head
  doxygen/doxygen.conf
  hcache/README.md
  hcache/backend.h
  hcache/bdb.c
  hcache/compr.h
  hcache/compr_lz4.c
  hcache/compr_zlib.c
  hcache/compr_zstd.c
  hcache/gdbm.c
  hcache/hcache.c
  hcache/kc.c
  hcache/lib.h
  hcache/lmdb.c
  hcache/qdbm.c
  hcache/tc.c
  init.c
  init.h
  mutt_config.c
  version.c
Labels: type:enhancement

#2139 Add abort_key config option
  globals.h
  gui/curs_lib.c
  keymap.c
  keymap.h
  main.c
  mutt_config.c
Labels: status:discuss, type:enhancement
