Repository neomutt/neomutt, pull requests merged in 2020-10, with the labels that each got.

#2682 build: improve ASAN flags
  auto.def
Labels: topic:build-process

#2685 Build with SASL and SSL when configuring with --everything
  auto.def
Labels: topic:autosetup

#2688 update/correct the sasl authentication methods
  conn/sasl.c
Labels: type:bug

#2680 Remove Address Book Global Variables
  alias/alias.c
  alias/config.c
  alias/dlgalias.c
  alias/dlgquery.c
  alias/gui.c
  alias/gui.h
  alias/lib.h
  alias/sort.c
  enter.c
  index.c
  pager.c
Labels: topic:refactoring

#2683 Move mx_check_empty into mx_ops
  compmbox/compress.c
  imap/imap.c
  maildir/maildir.c
  maildir/mh.c
  main.c
  mbox/mbox.c
  mx.c
  mx.h
  notmuch/notmuch.c
  pop/pop.c
Labels: topic:design, topic:refactoring

#2689 Refactor Maildir to use ARRAY
  Makefile.autosetup
  debug/graphviz.c
  hcache/config.c
  hcache/lib.h
  maildir/config.c
  maildir/edata.c
  maildir/edata.h
  maildir/lib.h
  maildir/maildir.c
  maildir/mdata.c
  maildir/mdata.h
  maildir/mdemail.c
  maildir/mdemail.h
  maildir/mh.c
  maildir/private.h
  maildir/sequence.c
  maildir/sequence.h
  maildir/shared.c
  notmuch/notmuch.c
Labels: topic:design, topic:maildir, topic:refactoring

#2695 libcompose remove config variables
  compose/compose.c
  compose/config.c
  compose/lib.h
  compose/private.h
  nntp/lib.h
  nntp/newsrc.c
  send/send.c
Labels: topic:design, topic:refactoring

#2696 add warning when signature file is missing or not readable
  send/send.c
Labels: type:bug

#2700 Respect "unsorted" order for mailboxes
  browser.c
  browser.h
  config/sort2.h
  core/mailbox.c
  core/mailbox.h
  docs/config.c
  mutt_config.c
  sidebar/config.c
  sidebar/sort.c
  test/config/dump.c
  test/config/helpers.c
  test/config/sort.c
Labels: type:enhancement

#2702 Handle the case where a mailbox is "folder"
  sidebar/window.c
Labels: bug:confirmed

#2703 Implement SMTP LOGIN auth mech
  send/smtp.c
Labels: type:enhancement

#2705 Indicate which folder we failed to browse
  imap/browse.c
  po/bg.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/et.po
  po/eu.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/hu.po
  po/id.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
Labels: type:enhancement
