Repository neomutt/neomutt, pull requests merged in 2020-06, with the labels that each got.

#2363 Refactor unsafe TAILQ returns
  browser.c
  command_parse.c
  core/mailbox.c
  core/neomutt.c
  core/neomutt.h
  email/rfc2231.c
  email/rfc2231.h
  email/tags.c
  imap/browse.c
  imap/imap.c
  init.c
  mutt/list.c
  mutt/list.h
  mutt_mailbox.c
  sendlib.c
  sidebar.c
  test/list/mutt_list_str_split.c
  test/neo/neomutt_mailboxlist_get_all.c
  test/rfc2231/rfc2231_encode_string.c
Labels: topic:refactoring, type:bug

#2372 hcache: fix keylen not being considered when building the full key
  hcache/hcache.c
Labels: bug:confirmed

#2380 Use the URL structure to compare the current mailbox with C_Spoolfile
  mx.c
Labels: bug:confirmed

#2390 re-open Mailbox after folder-hook
  index.c
Labels: type:bug

#2392 Teach link-thread to link all tagged emails
  context.c
  context.h
  index.c
  pager.c
Labels: bug:confirmed, type:enhancement

#2393 Avoid opening the same hcache file twice
  imap/imap.c
  imap/message.c
  imap/private.h
  imap/util.c
Labels: bug:confirmed, bug:crash

#2394 Adjust docs to intended behaviour
  docs/manual.xml.head
Labels: docs:manual

#2388 Allow renaming existing mailboxes
  command_parse.c
  sidebar.c
  sidebar.h
Labels: type:enhancement

#2389 Fix sidebar abbreviation / indentation for named-mailboxes
  sidebar.c
Labels: bug:confirmed, type:enhancement

#2405 Check folder against spoolfile by simple string comparison first
  mx.c
Labels: bug:confirmed

#2401 Refactor: Window architecture
  alias/dlgalias.c
  alias/dlgquery.c
  autocrypt/acct_menu.c
  browser.c
  compose.c
  conn/gui.c
  core/account.c
  core/mailbox.h
  core/neomutt.c
  gui/curs_lib.c
  gui/mutt_window.c
  gui/mutt_window.h
  index.c
  main.c
  mutt/notify.c
  mutt_history.c
  ncrypt/crypt_gpgme.c
  ncrypt/pgpkey.c
  ncrypt/smime.c
  postpone.c
  recvattach.c
  remailer.c
Labels: topic:design, topic:refactoring
