Repository neomutt/neomutt, pull requests merged in 2020-07, with the labels that each got.

#2385 Remove the built-in editor
  Makefile.autosetup
  compose.c
  docs/manual.xml.head
  docs/neomutt.man
  docs/neomutt.pwl
  edit.c
  edit.h
  main.c
  mutt_config.c
  send.c
  send.h
Labels: status:discuss, type:enhancement

#2406 move random functions to libmutt
  Makefile.autosetup
  auto.def
  main.c
  mutt/lib.h
  mutt/random.c
  mutt/random.h
  muttlib.c
  muttlib.h
  sendlib.c
Labels: topic:refactoring

#2412 create libsend for outgoing mail
  Makefile.autosetup
  alias/alias.c
  alias/dlgquery.c
  autocrypt/autocrypt.c
  browser.c
  commands.c
  compose.c
  copy.c
  index.c
  main.c
  mutt_attach.c
  mutt_body.c
  mutt_config.c
  mutt_globals.h
  mutt_header.c
  ncrypt/crypt.c
  ncrypt/crypt_gpgme.c
  ncrypt/pgp.c
  ncrypt/pgpkey.c
  ncrypt/smime.c
  pager.c
  pattern.c
  po/POTFILES.in
  postpone.c
  recvattach.c
  recvcmd.c
  recvcmd.h
  remailer.c
  send/body.c
  send/body.h
  send/config.c
  send/header.c
  send/header.h
  send/lib.h
  send/multipart.c
  send/multipart.h
  send/send.c
  send/send.h
  send/sendlib.c
  send/sendlib.h
  send/sendmail.c
  send/sendmail.h
  send/smtp.c
  send/smtp.h
  sendlib.c
  sendlib.h
Labels: topic:design

#2411 Track currently selected email by msgid
  compmbox/compress.c
  imap/imap.c
  index.c
  index.h
  maildir/maildir.c
  maildir/mh.c
  maildir/private.h
  maildir/shared.c
  mbox/mbox.c
  mutt/string.c
  mutt/string2.h
  mutt_header.c
  mx.c
  mx.h
  nntp/nntp.c
  notmuch/notmuch.c
  pager.c
  pop/pop.c
  postpone.c
Labels: type:enhancement

#2415 refactor icmd_set()
  icommands.c
Labels: topic:refactoring, type:bug

#2417 Convert libsend to use Config functions
  Makefile.autosetup
  alias/alias.c
  alias/dlgquery.c
  browser.c
  commands.c
  compose.c
  config/helpers.c
  config/helpers.h
  config/lib.h
  config/mbtable.c
  copy.c
  index.c
  main.c
  mutt/charset.c
  mutt_header.c
  ncrypt/crypt.c
  ncrypt/crypt_gpgme.c
  ncrypt/pgp.c
  ncrypt/pgpkey.c
  ncrypt/smime.c
  pager.c
  pattern.c
  recvattach.c
  recvcmd.c
  remailer.c
  send/body.c
  send/body.h
  send/header.c
  send/header.h
  send/send.c
  send/send.h
  send/sendlib.c
  send/sendlib.h
  send/sendmail.c
  send/sendmail.h
  send/smtp.c
  send/smtp.h
Labels: topic:design, topic:refactoring

#2418 feat: open neomutt with mailbox name
  main.c
  mx.c
  mx.h
Labels: type:enhancement

#2413 Optimize checking for the current email in the index
  index.c
  index.h
  pager.c
Labels: type:enhancement

#2421 Make the Sidebar more independent
  Makefile.autosetup
  command_parse.c
  command_parse.h
  index.c
  init.c
  main.c
  menu.c
  mutt_commands.c
  mutt_config.c
  mutt_globals.h
  pager.c
  sidebar/commands.c
  sidebar/functions.c
  sidebar/lib.h
  sidebar/observer.c
  sidebar/private.h
  sidebar/sidebar.c
  sidebar/wdata.c
Labels: topic:design, topic:refactoring

#2427 Fix: redrawing of pager_index_lines
  debug/window.c
  docs/config.c
  gui/mutt_window.c
  index.c
  test/Makefile.autosetup
  test/gui/visible.c
  test/main.c
Labels: type:bug

#2542 Refactor: Help Bar generation
  Makefile.autosetup
  alias/dlgalias.c
  alias/dlgquery.c
  autocrypt/dlgautocrypt.c
  browser.c
  commands.c
  compose.c
  conn/dlgverifycert.c
  debug/notify.c
  gui/curs_lib.c
  gui/dialog.c
  gui/mutt_window.c
  gui/mutt_window.h
  helpbar.c
  helpbar/config.c
  helpbar/helpbar.c
  helpbar/lib.h
  helpbar/private.h
  helpbar/wdata.c
  history/dlghistory.c
  index.c
  init.c
  menu.c
  mutt_config.c
  mutt_globals.h
  mutt_menu.h
  ncrypt/dlggpgme.c
  ncrypt/dlgpgp.c
  ncrypt/dlgsmime.c
  pager.c
  pattern/dlgpattern.c
  postpone.c
  recvattach.c
  remailer.c
  sidebar/sidebar.c
  test/pattern/dummy.c
Labels: status:discuss, topic:design, topic:refactoring

#2432 Allow index-style searching in postpone menu
  index.c
  menu.c
  mutt_menu.h
  pattern/lib.h
  pattern/pattern.c
  postpone.c
Labels: type:enhancement

#2545 Fix logic in checking an empty From address
  commands.c
Labels: bug:confirmed

#2544 add docs to config items
  autocrypt/config.c
  config/dump.c
  config/dump.h
  config/set.h
  conn/config.c
  docs/manual.xml.head
  hcache/config.c
  helpbar/config.c
  history/config.c
  imap/config.c
  init.c
  init.h
  maildir/config.c
  main.c
  mbox/config.c
  mutt_config.c
  ncrypt/config.c
  nntp/config.c
  notmuch/config.c
  pattern/config.c
  pop/config.c
  send/config.c
  sidebar/config.c
Labels: topic:config-file, type:enhancement

#2546 Fix retrieval of drafts when "postponed" is not in the mailboxes list
  imap/imap.c
  mx.c
  mx.h
Labels: bug:confirmed

#2547 Check for missing attachments in alternative parts
  recvattach.c
  send/send.c
  send/sendlib.c
Labels: bug:confirmed

#2552 Refresh current email after refreshing mailbox state
  index.c
Labels: bug:confirmed, bug:crash
