Repository neomutt/neomutt, pull requests merged in 2020-04, with the labels that each got.

#2218 Draft of pre-defined/pre-compiled regexes
  Makefile.autosetup
  conn/gnutls.c
  email/parse.c
  email/parse.h
  email/rfc2047.c
  email/url.c
  email/url.h
  main.c
  mutt/lib.h
  mutt/prex.c
  mutt/prex.h
  mutt/regex3.h
  test/Makefile.autosetup
  test/main.c
  test/parse/mutt_parse_mailto.c
  test/url/url_check_scheme.c
  test/url/url_new.c
  test/url/url_parse.c
  test/url/url_pct_decode.c
  test/url/url_pct_encode.c
Labels: topic:refactoring, type:enhancement

#2227 Use a precompiled regular expression in mutt_date_parse_date
  mutt/date.c
  mutt/date.h
  mutt/prex.c
  mutt/prex.h
  test/date/mutt_date_parse_date.c
Labels: topic:refactoring, type:enhancement

#2231 prex: convert mutt_date_parse_date_imap
  mutt/date.c
  mutt/prex.c
  mutt/prex.h
  test/date/mutt_date_parse_imap.c
Labels: topic:refactoring, type:enhancement

#2232 cirrus: update the local pkg db
  .cirrus.yml
Labels: topic:build-process

#2238 fix: mutt_date_add_timeout()
  mutt/date.c
  mutt/date.h
Labels: topic:testing, type:bug

#2244 add error for CLI empty emails
  send.c
Labels: type:bug

#2247 Only hide hidden mailboxes in Mailboxes view
  browser.c
Labels: bug:confirmed, bug:regression

#2198 Refactor the Compose screen
  address/address.c
  address/address.h
  compose.c
  index.c
  menu.c
  mutt_menu.h
Labels: topic:design, topic:refactoring

#2253 correct variable sizes
  conn/raw.c
  hcache/hcache.c
  hcache/hcachever.sh
  hcache/lib.h
  hcache/serialize.c
  hcache/serialize.h
  imap/command.c
  imap/imap_private.h
  imap/message.c
  imap/util.c
  maildir/shared.c
  mutt_logging.c
  progress.c
  progress.h
Labels: type:bug

#2257 Allow spaces before Day of Week
  mutt/prex.c
Labels: bug:confirmed

#2259 Add support for using PCRE2 in prex
  auto.def
  mutt/prex.c
Labels: type:enhancement

#2264 Centralize regex includes
  browser.c
  command_parse.c
  commands.c
  config/regex.c
  config/regex2.h
  conn/gnutls.c
  email/parse.c
  gui/color.c
  gui/color.h
  gui/curs_lib.c
  hook.c
  index.c
  menu.c
  mutt/charset.c
  mutt/prex.h
  mutt/regex.c
  mutt/regex3.h
  mutt_menu.h
  mutt_parse.c
  mutt_parse.h
  muttlib.c
  pager.c
  pattern.c
  pattern.h
  protos.h
  query.c
Labels: topic:refactoring

#2266 Update autosetup to upstream master
  autosetup/autosetup
  autosetup/autosetup-find-tclsh
  autosetup/cc.tcl
  autosetup/pkg-config.tcl
Labels: topic:build-process

#2270 ensure OP_NULL is always first
  opcodes.h
Labels: type:bug

#2279 build: tdb.h needs size_t, bring it in with stddef.h
  auto.def
Labels: bug:confirmed, topic:autosetup, topic:build-process

#2280 Fix finding pcre2 w/o pkgconf
  auto.def
Labels: bug:confirmed, topic:autosetup, topic:build-process

#2286 Handle pretty much anything in a URL query part
  mutt/prex.c
  test/url/url_parse.c
Labels: bug:confirmed, topic:notmuch

#2288 maildir: handle deleted emails correctly
  maildir/maildir.c
Labels: bug:confirmed, topic:maildir
