Repository neomutt/neomutt, pull requests merged in 2021-06, with the labels that each got.

#2947 window refactoring
  alias/dlgalias.c
  alias/dlgquery.c
  autocrypt/dlgautocrypt.c
  browser.c
  commands.c
  compose/cbar.c
  compose/compose.c
  conn/dlgverifycert.c
  flags.c
  gui/curs_lib.c
  gui/mutt_window.c
  gui/mutt_window.h
  gui/sbar.c
  gui/simple.c
  history/dlghistory.c
  index/ibar.c
  index/index.c
  index/observer.c
  menu/menu.c
  ncrypt/dlggpgme.c
  ncrypt/dlgpgp.c
  ncrypt/dlgsmime.c
  pager/do_pager.c
  pager/pager.c
  pager/pbar.c
  pattern/dlgpattern.c
  postpone.c
  recvattach.c
  remailer.c
Labels: topic:design, topic:refactoring

#2948 msgwin: factor out MessageWindow
  Makefile.autosetup
  commands.c
  enter.c
  flags.c
  gui/curs_lib.c
  gui/curs_lib.h
  gui/lib.h
  gui/msgwin.c
  gui/msgwin.h
  gui/mutt_window.c
  gui/mutt_window.h
  index/index.c
  keymap.c
  menu/draw.c
  menu/menu.c
  mutt_logging.c
  mutt_mailbox.c
  muttlib.c
  pager/pager.c
  po/POTFILES.in
  progress/progress.c
  recvattach.c
  recvcmd.c
Labels: topic:design, topic:refactoring

#2960 pager: add pager_read_delay
  contrib/samples/sample.neomuttrc
  docs/config.c
  docs/manual.xml.head
  pager/config.c
  pager/dlg_pager.c
Labels: status:discuss, type:enhancement

#2967 Handle emails without edata
  imap/message.c
Labels: bug:confirmed, bug:crash

#2963 Fix too strict assertion when viewing an attachment
  pager/dlg_pager.c
Labels: bug:confirmed, bug:crash

#2964 docs: Document pager_read_delay as a feature
  docs/manual.xml.head
Labels: docs:manual

#2968 Fix cleanup logic after resuming a draft
  postpone.c
Labels: bug:regression

#2974 hash: fix crash on element deletion
  mutt/hash.c
Labels: bug:crash

#2976 notmuch: really tolerate file renames behind neomutt's back
  notmuch/notmuch.c
Labels: topic:notmuch

#2979 pager: fix infinite loop
  pager/dlg_pager.c
Labels: type:bug

#2985 status: fix buffer overflow
  muttlib.c
Labels: bug:crash

#2983 skip quoted fixes
  docs/config.c
  docs/manual.xml.head
  opcodes.h
  pager/config.c
  pager/dlg_pager.c
Labels: topic:upstream
