Repository neomutt/neomutt, pull requests merged in 2021-12, with the labels that each got.

#3144 Fuzzing: Add CIFuzz
  .github/workflows/cifuzz.yml
Labels: topic:automation, topic:build-process, topic:testing, topic:stability, topic:security

#3151 imap: fix leak in imap_mailbox_rename()
  imap/browse.c
Labels: type:bug, topic:imap

#3153 build: configure --debug-queue
  auto.def
Labels: topic:build-process

#3155 refactor mutt_get_field()
  alias/alias.c
  alias/dlgquery.c
  browser/browser.c
  commands.c
  compose/functions.c
  conn/sasl.c
  imap/browse.c
  index/functions.c
  menu/menu.c
  mutt_header.c
  ncrypt/crypt_gpgme.c
  ncrypt/pgpkey.c
  ncrypt/smime.c
  pager/functions.c
  pattern/pattern.c
  recvcmd.c
  send/send.c
Labels: topic:refactoring, topic:design

#3164 Optionally keep an account alive on removal of its last mailbox
  compose/functions.c
  imap/command.c
  imap/imap.c
  index/functions.c
  mbox/mbox.c
  mx.c
  mx.h
  postpone.c
Labels: bug:confirmed, bug:crash

#3169 Fix selecting the right email after limiting
  index/functions.c
Labels: bug:confirmed

#3170 Fix restoring the selected message after limiting
  index/functions.c
Labels: bug:confirmed

#3171 Fix out of boundary write with long log lines
  mutt/logging.c
  mutt_logging.c
Labels: bug:confirmed, bug:crash
