Repository neomutt/neomutt, pull requests merged in 2021-05, with the labels that each got.

#2925 Escape message-ids in search macros generated with <mark-message>
  index/index.c
Labels: bug:confirmed

#2929 fix crash with uncoloured quotes
  gui/color.c
Labels: bug:crash

#2933 Unclutter the menu from mailbox / browser things
  browser.c
  browser.h
  menu/lib.h
  menu/menu.c
Labels: topic:refactoring

#2941 notmuch: refactor tag parsing
  Makefile.autosetup
  notmuch/lib.h
  notmuch/notmuch.c
  notmuch/tag.c
  notmuch/tag.h
  po/POTFILES.in
  test/Makefile.autosetup
  test/main.c
  test/notmuch/tag.c
Labels: topic:notmuch, topic:refactoring

#2946 create libprogress
  Makefile.autosetup
  commands.c
  imap/imap.c
  imap/message.c
  index/index.c
  maildir/maildir.c
  maildir/mh.c
  mbox/mbox.c
  nntp/nntp.c
  notmuch/mdata.c
  notmuch/mdata.h
  notmuch/notmuch.c
  pattern/pattern.c
  po/POTFILES.in
  pop/lib.c
  pop/pop.c
  progress/lib.h
  progress/progress.c
  send/smtp.c
  test/pattern/dummy.c
Labels: topic:design, topic:refactoring
