Repository neomutt/neomutt, pull requests merged in 2021-04, with the labels that each got.

#2879 observer: check global_data
  mutt/notify.c
Labels: type:bug

#2878 Do not remove "active" mailboxes
  command_parse.c
Labels: bug:confirmed, bug:crash

#2880 Don't propagate read-only state across reopens
  mx.c
Labels: bug:confirmed

#2883 Refuse to build without pcre2 when the pcre2-posix library is linked in
  auto.def
Labels: topic:build-process

#2868 pager refactoring
  commands.c
  gui/curs_lib.c
  gui/curs_lib.h
  help.c
  icommands.c
  index/index.c
  mutt_attach.c
  ncrypt/dlggpgme.c
  ncrypt/dlgpgp.c
  pager/lib.h
  pager/pager.c
  send/sendmail.c
Labels: status:discuss, topic:design, topic:refactoring

#2854 Provide a mean to turn off wrapping output of mailcap commands
  commands.c
  docs/manual.xml.head
  email/body.h
  handler.c
  mailcap.c
  mailcap.h
  mutt_attach.c
Labels: type:enhancement

#2888 Move state to libmutt, deglobalize it
  Makefile.autosetup
  copy.c
  enriched.c
  handler.c
  init.c
  mutt/lib.h
  mutt/state.c
  mutt/state.h
  mutt_attach.c
  mutt_globals.h
  ncrypt/crypt.c
  ncrypt/crypt_gpgme.c
  ncrypt/pgp.c
  ncrypt/pgpmicalg.c
  ncrypt/smime.c
  pager/pager.c
  pattern/exec.c
  postpone.c
  recvattach.c
  recvcmd.c
  rfc3676.c
  send/sendlib.c
Labels: topic:refactoring

#2892 limit observer callbacks to a single type
  mutt/notify.c
Labels: topic:design

#2896 compose: pass Email to pager
  compose/compose.c
Labels: type:bug

#2899 formats: drop Mailbox param
  attachments.c
  hdrline.c
  pager/pager.c
  recvattach.c
  recvcmd.c
  recvcmd.h
  send/send.c
  send/send.h
Labels: status:discuss, topic:refactoring

#2901 index_format: make %B a synonym of %K
  docs/config.c
  hdrline.c
Labels: type:enhancement

#2910 Get rid of the Colors global variable
  gui/color.c
  gui/color.h
  gui/curs_lib.c
  gui/mutt_curses.c
  index/index.c
  init.c
  main.c
  menu.c
  mutt_globals.h
  pager/pager.c
  progress.c
  sidebar/window.c
Labels: bug:confirmed, bug:crash

#2914 Focus the logs pager view to the bottom
  index/index.c
  pager/lib.h
  pager/pager.c
Labels: type:enhancement

#2916 fix crash in msg_search()
  pattern/exec.c
Labels: type:bug

#2923 hcache: preserve Email->notify
  hcache/hcache.c
Labels: bug:crash
