Repository neomutt/neomutt, pull requests merged in 2021-09, with the labels that each got.

#3030 notmuch: handle missing libnotmuch version bumps
  notmuch/db.c
  notmuch/notmuch.c
  notmuch/private.h
Labels: topic:notmuch

#3034 pager: split up 1400 line switch statement
  Makefile.autosetup
  pager/dlg_pager.c
  pager/functions.c
  pager/functions.h
  pager/lib.h
  pager/private_data.c
  pager/private_data.h
  po/POTFILES.in
Labels: topic:refactoring

#3038 Kill GreetingInfo (refactor)
  send/send.c
Labels: topic:refactoring

#3037 Implement list-(un)subscribe
  attach/dlg_attach.c
  debug/email.c
  debug/graphviz.c
  docs/manual.xml.head
  email/envelope.c
  email/envelope.h
  email/parse.c
  email/parse.h
  functions.c
  hcache/serialize.c
  imap/message.c
  index/functions.c
  opcodes.h
  pager/functions.c
  send/send.c
  send/send.h
Labels: type:enhancement

#3041 Do not attempt to copy from a FILE* onto itself
  copy.c
  maildir/maildir.c
  maildir/mh.c
Labels: bug:confirmed
