Repository neomutt/neomutt, pull requests merged in 2021-03, with the labels that each got.

#2837 Fix mailboxes command for Maildir
  docs/manual.xml.head
Labels: docs:manual

#2827 Cache an Email's tags in the header cache
  email/tags.c
  email/tags.h
  hcache/hcache.c
  hcache/hcachever.sh
  hcache/serialize.c
  hcache/serialize.h
Labels: bug:confirmed

#2839 Fix caching new labels in the header cache
  imap/imap.c
Labels: bug:confirmed

#2842 Skip installing empty manual.txt if lynx/w3m/elinks is not available
  docs/Makefile.autosetup
Labels: bug:confirmed

#2845 List-expand CC in [exec]
  auto.def
Labels: bug:confirmed, topic:autosetup, topic:build-process

#2846 Move MX APIs into core
  compmbox/lib.h
  core/lib.h
  core/mxapi.h
  imap/lib.h
  maildir/lib.h
  mbox/lib.h
  mx.h
  nntp/lib.h
  notmuch/lib.h
  pop/lib.h
Labels: topic:refactoring

#2864 Fix crash in failure to decrypt a postponed message
  postpone.c
Labels: bug:confirmed, bug:crash

#2856 Cleanup account data when closing the last mailbox
  core/account.c
  imap/imap.c
  mx.c
Labels: bug:confirmed, topic:imap

#2862 Allow a -noregex param to folder and mbox hooks
  docs/manual.xml.head
  docs/neomuttrc.man.head
  hook.c
Labels: type:enhancement

#2870 refactor: Don't use the global Context when not necessary
  alias/dlgalias.c
  alias/dlgquery.c
  commands.c
  commands.h
  copy.c
  copy.h
  gui/color.c
  hook.c
  imap/imap.c
  index/index.c
  init.c
  pattern/compile.c
  pattern/lib.h
  pattern/pattern.c
  postpone.c
  score.c
  test/pattern/comp.c
Labels: topic:design, topic:refactoring

#2869 refactor: commands that require a Context
  Makefile.autosetup
  alias/alias.c
  alternates.c
  alternates.h
  attachments.c
  attachments.h
  command_parse.c
  commands.c
  email/globals.c
  email/globals.h
  hdrline.c
  index/observer.c
  init.c
  main.c
  mutt/notify_type.h
  mutt_globals.h
  mutt_parse.c
  ncrypt/crypt.c
  nntp/nntp.c
  pattern/exec.c
  po/POTFILES.in
  recvattach.c
  send/send.c
  send/sendlib.c
  subjectrx.c
  subjectrx.h
Labels: topic:design, topic:refactoring
