Repository neomutt/neomutt, pull requests merged in 2021-08, with the labels that each got.

#3018 notmuch: open database with user's configuration
  auto.def
  notmuch/db.c
Labels: topic:notmuch

#3023 stats: don't check mailbox stats unless told
  mutt_mailbox.c
Labels: type:bug

#3026 build: strip back curses checks
  auto.def
  color/color.c
  gui/mutt_curses.c
  gui/terminal.c
  main.c
  menu/draw.c
  mutt_commands.c
  pager/display.c
  version.c
Labels: topic:build-process

#3028 It looks like we don't have a context when viewing a RFC822 attachment
  pager/dlg_pager.c
Labels: bug:crash

#3031 notmuch: remove duplicate filename logic
  notmuch/notmuch.c
Labels: topic:notmuch
