Repository neomutt/neomutt, pull requests merged in 2021-07, with the labels that each got.

#2998 notmuch: implement query window reset functionality
  docs/manual.xml.head
  functions.c
  index/dlg_index.c
  notmuch/lib.h
  notmuch/notmuch.c
  opcodes.h
Labels: topic:notmuch, type:enhancement

#2991 Add $use_threads config variable
  commands.c
  compose/compose.c
  contrib/samples/sample.neomuttrc
  contrib/samples/sample.neomuttrc-tlr
  docs/config.c
  docs/manual.xml.head
  email/thread.c
  email/thread.h
  flags.c
  hdrline.c
  index/dlg_index.c
  index/index.c
  mutt_config.c
  mutt_thread.c
  mutt_thread.h
  score.c
  sort.c
  status.c
Labels: status:ready, type:enhancement

#3006 index: refactor functions
  Makefile.autosetup
  index/dlg_index.c
  index/functions.c
  index/functions.h
  index/lib.h
  index/private_data.h
  po/POTFILES.in
Labels: topic:design, topic:refactoring

#3002 notmuch: show additional mail in query windows
  docs/config.c
  docs/manual.xml.head
  notmuch/config.c
  notmuch/notmuch.c
  notmuch/query.c
  notmuch/query.h
  test/notmuch/window_query.c
Labels: topic:notmuch, type:enhancement

#3013 Fix tag-prefix tag
  index/functions.c
Labels: bug:confirmed

#3009 unlink mailbox when freeing account
  core/account.c
  sidebar/sidebar.c
Labels: bug:crash, topic:notmuch
