Repository neomutt/neomutt, pull requests merged in 2022-01, with the labels that each got.

#3185 pattern: fix leak
  pattern/compile.c
Labels: type:bug

#3186 fix leak of threads
  mutt/hash.c
Labels: type:bug

#3177 Refactor uses of global Context
  alias/dlgquery.c
  autocrypt/autocrypt.c
  color/regex.c
  compose/compose.c
  copy.c
  hook.c
  index/index.c
  index/lib.h
  init.c
  main.c
  menu/draw.c
  menu/menu.c
  monitor.c
  score.c
  send/sendlib.c
Labels: bug:crash, topic:refactoring

#3173 Improve composition of multipart messages
  attach/recvattach.c
  compose/compose.c
  compose/functions.c
  docs/manual.xml.head
  email/attach.c
  email/attach.h
  functions.c
  opcodes.h
  postpone.c
  send/send.c
Labels: topic:refactoring, type:enhancement, topic:design

#3201 Say which file exists when saving attachments
  muttlib.c
Labels: type:enhancement

#3218 fix crash when forwarding attachments
  mutt_body.c
Labels: bug:crash

#3220 Avoid infinite loop in OptNoCurses mode
  gui/curs_lib.c
Labels: bug:confirmed

#3197 Add support for composing 'multipart/related' emails
  compose/functions.c
  docs/manual.xml.head
  email/parse.c
  functions.c
  opcodes.h
  send/header.c
Labels: status:discuss, type:enhancement

#3224 fix screen mode after attempting decryption
  gui/curs_lib.c
Labels: type:bug
