Repository neomutt/neomutt, pull requests merged in 2022-06, with the labels that each got.

#3434 muttlib/mutt_expando_format: allow for longer expansions in e.g. index_format
  muttlib.c
Labels: type:bug

#3440 Fix debug_file ignored #3394
  main.c
Labels: type:bug

#3433 Move relevant parts of contrib into data
  Makefile.autosetup
  auto.def
  contrib/Makefile.autosetup
  contrib/README.md
  data/Makefile.autosetup
  data/README.md
  data/account-command/README.md
  data/account-command/gpg-json/README.md
  data/account-command/gpg-json/credentials.sh
  data/account-command/macos-keychain/README.md
  data/account-command/macos-keychain/keychain.py
  data/colorschemes/neonwolf-256.neomuttrc
  data/colorschemes/solarized-dark-256.neomuttrc
  data/colorschemes/vombatidae.neomuttrc
  data/colorschemes/zenburn.neomuttrc
  data/logo/neomutt-128.png
  data/logo/neomutt-256.png
  data/logo/neomutt-32.png
  data/logo/neomutt-64.png
  data/logo/neomutt.svg
  data/mime.types
  docs/Makefile.autosetup
Labels: status:discuss

#3447 buffer: fix runaway memory allocation
  mutt/buffer.c
Labels: type:bug

#3443 Add encryption and decryption pipes to arg parser
  contrib/oauth2/mutt_oauth2.py
  contrib/oauth2/mutt_oauth2.py.README
Labels: type:enhancement

#3449 Fix a leak on failure to decode a RFC2047 header
  email/rfc2047.c
Labels: bug:leak

#3448 Refactor auto-completion code
  Makefile.autosetup
  complete/complete.c
  complete/data.c
  complete/data.h
  complete/helpers.c
  complete/lib.h
  enter/functions.c
  enter/wdata.h
  enter/window.c
  init.c
  main.c
  notmuch/lib.h
  notmuch/notmuch.c
Labels: topic:refactoring
