Repository neomutt/neomutt, pull requests merged in 2022-04, with the labels that each got.

#3337 Index: refactor resolve
  index/functions.c
Labels: topic:refactoring

#3333 Split the Index/Pager (Part 1)
  gui/curs_lib.c
  index/dlg_index.c
  index/functions.c
  index/lib.h
  index/private_data.h
  index/shared_data.c
  pager/dlg_pager.c
  pager/functions.c
  pager/lib.h
  pager/message.c
  pager/pager.c
  pager/private_data.h
Labels: topic:refactoring, topic:design

#3338 index: fix indicator for mini-Index
  index/dlg_index.c
Labels: type:bug

#3329 Issue warnings on duplicate keys
  command_parse.c
Labels: type:enhancement

#3344 Force checking stats when launching with -Z
  browser/browser.c
  commands.c
  commands.h
  core/mxapi.h
  gui/global.c
  imap/imap.c
  index/dlg_index.c
  maildir/maildir.c
  main.c
  mbox/mbox.c
  mutt_mailbox.c
  mutt_mailbox.h
  status.c
Labels: bug:confirmed

#3351 Fix forwarding text attachments when honor_disposition is set
  handler.c
  handler.h
  send/send.c
Labels: bug:confirmed

#3358 docs: fix example multipart/alternative compose macro
  docs/manual.xml.head
Labels: docs:manual

#3354 color: disable mono command
  color/command.c
Labels: status:discuss

#3347 index: merge more colours
  color/quoted.c
  compose/cbar.c
  envelope/window.c
  gui/curs_lib.c
  gui/msgwin.c
  gui/sbar.c
  helpbar/helpbar.c
  index/dlg_index.c
  index/ibar.c
  keymap.c
  menu/draw.c
  pager/display.c
  pager/pager.c
  pager/pbar.c
  progress/progress.c
  question/question.c
  sidebar/window.c
Labels: type:bug

#3366 fix: misalignment of mini-index
  index/functions.c
Labels: type:bug

#3365 fix: clearing color with default
  color/regex.c
  pager/display.c
Labels: bug:crash

#3352 Kill global and Propagate display attach status through State
  attach/mutt_attach.c
  handler.c
  mutt/state.h
  options.h
Labels: topic:refactoring, topic:design

#3378 Make sure the index redraws all that's needed
  index/index.c
Labels: bug:confirmed

#3379 index: fix menu size on new mail
  index/index.c
Labels: type:bug

#3381 mbox: fix sync duplicates
  mbox/mbox.c
Labels: type:bug

#3382 generic: split out OP_EXIT binding
  functions.c
Labels: type:bug

#3385 Fix parsing of sendmail cmd
  send/sendmail.c
Labels: type:bug

#3380 fix: stuck browser cursor
  browser/browser.c
Labels: type:bug

#3388 Don't overlimit LMDB mmap size
  store/lmdb.c
Labels: type:bug
