Repository neomutt/neomutt, pull requests merged in 2022-03, with the labels that each got.

#3270 Unify Alias and Query with function dispatcher
  Makefile.autosetup
  alias/dlgalias.c
  alias/dlgquery.c
  alias/functions.c
  alias/functions.h
  alias/gui.c
  alias/gui.h
  alias/lib.h
  functions.c
  index/functions.c
  opcodes.h
  pattern/pattern.c
Labels: topic:refactoring, topic:design

#3284 menu: fix repainting of arrow_cursor/indicator
  menu/draw.c
Labels: type:bug

#3290 Force SMTP authentication if smtp_user is set
  send/smtp.c
Labels: bug:confirmed

#3292 Plug a leak in mutt_pattern_comp
  pattern/compile.c
  test/Makefile.autosetup
  test/main.c
  test/pattern/leak.c
Labels: bug:confirmed, bug:leak

#3296 fix selecton after <limit>
  index/functions.c
Labels: type:bug

#3301 query: fix crashes
  alias/dlg_alias.c
  alias/dlg_query.c
  alias/functions.c
  alias/lib.h
  index/functions.c
Labels: bug:crash

#3303 Make sure we have enough memory for a new email
  imap/message.c
Labels: bug:confirmed, bug:crash

#3308 Pre-2022-03-31 warning/debashification pass
  conn/sasl.c
  context.c
  contrib/keybase/install.sh
  contrib/oauth2/mutt_oauth2.py.README
  docs/manual.xml.head
  gui/curs_lib.c
  gui/curs_lib.h
  mutt/regex.c
  timegm.c
Labels: topic:build-process

#3315 Index/Pager: use the global function dispatcher
  commands.c
  core/neomutt.h
  index/dlg_index.c
  index/functions.c
  index/index.c
  pager/dlg_pager.c
  pager/functions.c
  pager/pager.c
Labels: topic:refactoring

#3314 mutt_parse_charset_hook() / mutt_parse_iconv_hook() added
  hook.c
  hook.h
  mutt_commands.c
Labels: topic:refactoring

#3316 Do not insert an actual key mapping for noop
  keymap.c
Labels: bug:confirmed

#3320 global: move show-log-messages
  functions.c
  gui/global.c
  index/functions.c
Labels: topic:refactoring

#3326 Fix memory leak in tag-transforms and tag-formats
  command_parse.c
  email/tags.c
  email/tags.h
  init.c
  mutt_globals.h
Labels: topic:refactoring, bug:leak
