Repository neomutt/neomutt, pull requests merged in 2023-04, with the labels that each got.

#3815 address: use bitmasks to detect special characters
  address/address.c
Labels: topic:refactoring

#3811 Roundup but for warnings
  pop/pop.c
  send/send.c
Labels: topic:refactoring

#3818 build: refactor testing
  Makefile.autosetup
  auto.def
  test/Makefile.autosetup
Labels: topic:build-process, topic:testing

#3825 Only add the root SRCDIR to VPATH
  auto.def
Labels: topic:build-process

#3826 Fix crash with the iconv cache
  mutt/charset.c
Labels: bug:confirmed, bug:crash

#3806 Use Buffer in mutt_rfc822_read_line
  email/parse.c
  email/parse.h
  pattern/exec.c
  test/parse/mutt_rfc822_read_line.c
Labels: topic:refactoring

#3804 email: call ftello() less
  email/parse.c
Labels: topic:refactoring

#3792 Make $pager_index_lines use a fixed number of rows
  docs/config.c
  pager/message.c
  pager/pager.c
Labels: type:discuss, type:enhancement

#3699 Implement 24bit colors aka truecolor
  auto.def
  color/command.c
  color/curses.c
  docs/config.c
  docs/manual.xml.head
  docs/neomuttrc.man.head
  init.c
  mutt_config.c
  parse/extract.h
Labels: type:enhancement
