Repository neomutt/neomutt, pull requests merged in 2023-08, with the labels that each got.

#3951 bring IndexSharedData notifications back
  index/shared_data.c
Labels: type:bug

#3957 fix mview leak
  mview.c
Labels: bug:leak

#3956 fix 'from' address when real name isn't set
  send/send.c
  send/sendlib.c
Labels: type:bug

#3949 Add bool browser_sort_dirs_first, always putting directories first
  browser/config.c
  browser/dlg_browser.c
  browser/sort.c
  docs/config.c
Labels: type:discuss, type:enhancement

#3961 fix macOS build
  init.c
Labels: topic:build-process, type:bug

#3962 bug: fix limited threads
  index/functions.c
  mutt_thread.c
Labels: bug:crash

#3953 replace qsort() with mutt_qsort_r()
  alias/sort.c
  browser/sort.c
  commands.c
  complete/helpers.c
  config/subset.c
  config/subset.h
  core/command.c
  imap/imap.c
  imap/message.c
  imap/msg_set.c
  imap/msg_set.h
  maildir/maildir.c
  maildir/mh.c
  mutt/array.h
  mutt_thread.c
  muttlib.c
  ncrypt/dlg_gpgme.c
  ncrypt/dlg_pgp.c
  sidebar/sort.c
  sort.c
  sort.h
  test/array/mutt_array_api.c
  test/config/dump.c
  test/imap/msg_set.c
Labels: topic:refactoring

#3973 change recode_buf() to take a Buffer
  alias/alias.c
Labels: topic:refactoring

#3985 browser: fix completion
  enter/functions.c
Labels: type:bug

#3988 pager: fix search crash
  pager/display.c
Labels: bug:crash

#3982 `mailboxes`: add `-label`, `-notify` and `-poll` options
  browser/dlg_browser.c
  browser/lib.h
  commands.c
  core/mailbox.c
  core/mailbox.h
  docs/manual.xml.head
  docs/neomuttrc.man.head
  imap/imap.c
  mutt_mailbox.c
  nntp/browse.c
  sidebar/window.c
Labels: type:enhancement

#3974 remove dead code in nntp_select_server()
  nntp/newsrc.c
Labels: topic:refactoring

#3978 Add a check in `index_function_dispatcher`
  index/functions.c
Labels: bug:crash

#3989 move config/cache to core library
  Makefile.autosetup
  config/lib.h
  convert/content_info.c
  core/config_cache.c
  core/config_cache.h
  core/lib.h
  imap/utf7.c
  test/Makefile.autosetup
  test/core/config_cache.c
  test/main.c
Labels: topic:refactoring

#3992 move config address type to address library
  Makefile.autosetup
  address/config_type.c
  address/config_type.h
  address/lib.h
  config/address.h
  config/helpers.c
  config/helpers.h
  config/lib.h
  test/Makefile.autosetup
  test/address/config_type.c
  test/config/helpers.c
  test/main.c
Labels: topic:refactoring, topic:build-process

#3995 move mutt_history.c to history lib
  Makefile.autosetup
  enter/functions.c
  history/history.c
  history/lib.h
  main.c
  mutt_history.c
  mutt_history.h
  test/pattern/dummy.c
Labels: topic:refactoring

#3999 help: fix search highlight
  pager/display.c
Labels: type:bug

#4015 build: more robust pkgconf check for lua
  auto.def
Labels: topic:build-process

#3998 eliminate global OptIgnoreMacroEvents
  alias/dlg_alias.c
  alias/dlg_query.c
  attach/dlg_attach.c
  autocrypt/autocrypt.c
  autocrypt/dlg_autocrypt.c
  browser/dlg_browser.c
  compose/dlg_compose.c
  conn/dlg_verifycert.c
  enter/functions.c
  enter/window.c
  flags.c
  globals.c
  globals.h
  gui/curs_lib.c
  gui/curs_lib.h
  history/dlg_history.c
  index/dlg_index.c
  keymap.c
  keymap.h
  mixmaster/dlg_mixmaster.c
  ncrypt/dlg_gpgme.c
  ncrypt/dlg_pgp.c
  ncrypt/dlg_smime.c
  pager/dlg_pager.c
  pager/message.c
  pattern/dlg_pattern.c
  postpone/dlg_postpone.c
  question/question.c
Labels: topic:refactoring
