Repository neomutt/neomutt, pull requests merged in 2023-10, with the labels that each got.

#4056 msgwin: check for dupe text
  gui/msgwin.c
Labels: bug:crash

#4060 fix crash on exit
  gui/rootwin.c
Labels: bug:crash

#4061 fix header colour
  pager/display.c
Labels: type:bug

#4064 fix 32-bit date overflow
  mutt/date.c
Labels: type:bug

#4078 fix new mail in limited view
  index/dlg_index.c
Labels: type:bug

#4067 remove unused count of new mails from index private data
  index/dlg_index.c
  index/private_data.c
  index/private_data.h
Labels: topic:refactoring

#4080 pager: add save function
  pager/functions.c
Labels: type:enhancement

#4082 fix file auto-completion
  alias/alias.c
  attach/recvattach.c
  browser/complete.c
  compose/functions.c
  muttlib.c
Labels: type:bug

#4073 color: refactor parsing
  color/ansi.c
  color/ansi.h
  color/attr.c
  color/attr.h
  color/color.c
  color/command.c
  color/command2.h
  color/curses.c
  color/merged.c
  color/parse_ansi.c
  color/parse_color.c
  color/parse_color.h
  color/quoted.c
  color/quoted.h
  color/regex.c
  color/regex4.h
  color/simple.c
  color/simple2.h
  pager/display.c
Labels: topic:refactoring

#4090 Mx alloc overhead reduction
  mx.c
Labels: topic:refactoring, type:bug

#4093 remove mutt_path_concat()
  browser/functions.c
  mutt/path.c
  mutt/path.h
  test/Makefile.autosetup
  test/main.c
  test/path/mutt_path_concat.c
Labels: topic:refactoring
