Repository neomutt/neomutt, pull requests merged in 2023-05, with the labels that each got.

#3842 Allow percentage i18n
  pager/pbar.c
  progress/window.c
  status.c
Labels: topic:translation, type:enhancement

#3846 Select the first email when coming from an empty limit
  index/functions.c
Labels: bug:confirmed

#3845 Refactor MxOps->msg_open() to eliminate msgno
  compmbox/compress.c
  copy.c
  core/mxapi.h
  external.c
  hdrline.c
  imap/message.c
  imap/private.h
  index/functions.c
  maildir/lib.h
  maildir/maildir.c
  maildir/mh.c
  mbox/mbox.c
  mx.c
  mx.h
  ncrypt/crypt.c
  nntp/nntp.c
  notmuch/notmuch.c
  pager/message.c
  pattern/exec.c
  pop/pop.c
  postpone/postpone.c
  send/send.c
  send/sendlib.c
  test/pattern/dummy.c
Labels: topic:refactoring

#3861 Stop parsing headers at the end of the headers section
  email/parse.c
Labels: bug:confirmed

#3863 Fix keymap comparison
  keymap.c
Labels: bug:confirmed

#3864 color: fix handling of bright
  color/command.c
Labels: type:bug

#3866 test: use a real FILE pointer
  test/attach/mutt_actx_add_fp.c
  test/charset/mutt_ch_fgetconv_open.c
  test/file/mutt_file_copy_bytes.c
  test/file/mutt_file_copy_stream.c
  test/file/mutt_file_iter_line.c
  test/file/mutt_file_map_lines.c
  test/file/mutt_file_read_line.c
  test/parse/mutt_parse_multipart.c
  test/parse/mutt_parse_part.c
  test/parse/mutt_rfc822_parse_message.c
  test/parse/mutt_rfc822_read_line.c
Labels: topic:testing, type:bug

#3868 drop notification relays
  index/shared_data.c
Labels: topic:refactoring

#3869 imap: move $delete_untag out
  external.c
  imap/message.c
  mx.c
Labels: topic:refactoring

#3872 Replace el_add_tagged() with ea_add_tagged()
  editmsg.c
  email/email.c
  email/email.h
  external.c
  external.h
  flags.c
  imap/lib.h
  imap/message.c
  index/functions.c
  mutt_header.c
  mutt_header.h
  mutt_thread.c
  mutt_thread.h
  mview.c
  mview.h
  mx.c
  ncrypt/crypt.c
  ncrypt/lib.h
  protos.h
  recvcmd.c
  send/send.c
  send/send.h
  test/Makefile.autosetup
  test/email/emaillist_add_email.c
  test/email/emaillist_clear.c
  test/main.c
Labels: topic:refactoring

#3873 Respect --[disable-]fmemopen in tests
  test/convert/mutt_convert_file_from_to.c
  test/convert/mutt_convert_file_to.c
  test/parse/mutt_rfc822_read_line.c
  test/test_common.h
Labels: topic:refactoring, topic:testing

#3878 fix "certificate saved" message
  conn/gnutls.c
Labels: type:bug

#3871 Devel/color colorschemes
  color/command.c
Labels: topic:refactoring

#3877 imap: factor out tagged emails
  Makefile.autosetup
  imap/imap.c
  imap/message.c
  imap/msg_set.c
  imap/msg_set.h
  test/Makefile.autosetup
  test/imap/msg_set.c
  test/main.c
Labels: topic:refactoring, topic:imap
