Repository neomutt/neomutt, pull requests merged in 2023-02, with the labels that each got.

#3647 Finished spanish translation
  po/es.po
Labels: topic:translation

#3657 Document that $forward_decrypt is not PGP only
  docs/config.c
Labels: docs:manual

#3659 Rename sidebar_whitelist to sidebar_pin
  ChangeLog.md
  alternates.c
  docs/config.c
  docs/manual.xml.head
  docs/neomuttrc.man.head
  email/globals.h
  sidebar/commands.c
  sidebar/observer.c
  sidebar/private.h
  sidebar/sidebar.c
  sidebar/window.c
Labels: type:enhancement

#3664 Recognise text/vcard as not an attachment
  docs/manual.xml.head
  docs/neomuttrc.head
Labels: docs:manual

#3666 Fix bug: hdr_order did not sort last header correctly
  copy.c
Labels: type:bug

#3669 Fix a double-free crash when using :fetch-mail
  pop/pop.c
Labels: bug:crash

#3673 Make exiting via SIGINT more graceful
  gui/curs_lib.c
Labels: type:enhancement

#3674 ifdef: check for store names
  command_parse.c
  docs/manual.xml.head
  docs/neomuttrc.man.head
Labels: type:enhancement

#3708 Check before dereference
  pager/pager.c
Labels: bug:crash

#3702 Rename connect_timeout to socket_timeout, use it for read/write ops too
  conn/config.c
  conn/raw.c
  docs/config.c
Labels: type:enhancement

#3719 Let $indent_string, $post_indent_string respect $attribution_locale
  copy.c
  recvcmd.c
  send/send.c
Labels: type:bug

#3718 Document alternatives to $date_format
  docs/config.c
Labels: docs:manual

#3726 colour postponed email
  postpone/dlg_postpone.c
Labels: type:enhancement

#3729 Identify compiler
  auto.def
Labels: topic:build-process

#3733 debug: fix email debugging
  Makefile.autosetup
  debug/common.c
  debug/email.c
  debug/graphviz.c
  debug/lib.h
Labels: type:bug

#3730 Fix decryption issue when postponing S/MIME encrypted mails
  postpone/postpone.c
Labels: type:bug

#3742 config: fix initial values
  init.c
Labels: type:bug

#3748 sidebar: add background colour
  color/color.h
  color/command.c
  docs/config.c
  docs/manual.xml.head
  docs/neomuttrc.man.head
  sidebar/observer.c
  sidebar/window.c
Labels: type:enhancement
