Repository neomutt/neomutt, pull requests merged in 2023-03, with the labels that each got.

#3752 sidebar: allow an empty divider
  docs/config.c
  sidebar/config.c
  sidebar/observer.c
  sidebar/private.h
  sidebar/window.c
Labels: type:enhancement, type:bug

#3723 Rewording around Regex and Pattern
  docs/config.c
  docs/manual.xml.head
  docs/neomuttrc.man.head
  hook.c
Labels: docs:manual

#3760 Populate ChangeLog for the next release
  .mailmap
  AUTHORS.md
  ChangeLog.md
  README.md
Labels: type:enhancement

#3785 lua: fix command registration
  mutt_lua.c
Labels: topic:lua-scripting, type:bug

#3787 build: tidy Makefiles, fix race condition
  Makefile.autosetup
  contrib/Makefile.autosetup
  data/Makefile.autosetup
  docs/Makefile.autosetup
  po/Makefile.autosetup
Labels: topic:refactoring, topic:build-process, type:bug

#3777 pager: add helper for getting $pager
  attach/mutt_attach.c
  copy.c
  help.c
  index/functions.c
  mutt_config.c
  pager/config.c
  pager/do_pager.c
  pager/lib.h
Labels: topic:refactoring
