Repository neomutt/neomutt, pull requests merged in 2023-12, with the labels that each got.

#4119 Fix Header Cache Key Handling
  hcache/hcache.c
  imap/mdata.c
  imap/message.c
  imap/util.c
  maildir/maildir.c
Labels: topic:refactoring, type:bug, topic:hcache

#4124 config: fix flag overlaps
  config/charset.h
  config/sort2.h
  config/types.h
  mutt/regex3.h
  mutt/slist.h
Labels: type:bug

#4125 compose: restore view-text/pager/mailcap
  compose/functions.c
Labels: type:enhancement, type:bug

#4126 alias: add tags
  alias/alias.c
  alias/alias.h
  alias/commands.c
  alias/dlg_alias.c
  alias/dlg_query.c
  alias/lib.h
  mutt/prex.c
  mutt/prex.h
  pattern/exec.c
  test/pattern/dummy.c
Labels: type:enhancement

#4131 move editor test code
  editor/enter.c
  editor/enter.h
  test/Makefile.autosetup
  test/editor/common.c
  test/editor/common.h
  test/editor/editor_backspace.c
  test/editor/editor_backward_char.c
  test/editor/editor_backward_word.c
  test/editor/editor_bol.c
  test/editor/editor_buffer_get_cursor.c
  test/editor/editor_buffer_is_empty.c
  test/editor/editor_buffer_set.c
  test/editor/editor_buffer_set_cursor.c
  test/editor/editor_case_word.c
  test/editor/editor_delete_char.c
  test/editor/editor_eol.c
  test/editor/editor_forward_char.c
  test/editor/editor_forward_word.c
  test/editor/editor_kill_eol.c
  test/editor/editor_kill_eow.c
  test/editor/editor_kill_line.c
  test/editor/editor_kill_whole_line.c
  test/editor/editor_kill_word.c
  test/editor/editor_transpose_chars.c
  test/main.c
Labels: topic:refactoring

#4133 move log_disp_null() into test folder
  fuzz/address.c
  mutt/logging.c
  mutt/logging2.h
  test/Makefile.autosetup
  test/color/curses.c
  test/color/simple.c
  test/common.c
  test/compress/lz4.c
  test/compress/zlib.c
  test/compress/zstd.c
  test/file/mutt_file_lock.c
  test/logging/log_disp_null.c
  test/main.c
  test/memory/mutt_mem_malloc.c
  test/parse/mutt_parse_multipart.c
  test/test_common.h
Labels: topic:refactoring

#4135 remove unused functions
  config/quad.c
  config/quad.h
  config/subset.c
  config/subset.h
  gui/curs_lib.c
  gui/curs_lib.h
  mutt/buffer.c
  mutt/buffer.h
  mutt/file.c
  mutt/file.h
  mutt/slist.c
  mutt/slist.h
  test/Makefile.autosetup
  test/buffer/buf_upper.c
  test/config/quad.c
  test/config/slist.c
  test/config/subset.c
  test/file/mutt_file_chmod.c
  test/file/mutt_file_chmod_rm.c
  test/main.c
  test/slist/slist_add_list.c
  test/slist/slist_empty.c
Labels: topic:refactoring

#4138 remove unused function mutt_socket_write()
  .github/unused.sh
  conn/socket.c
  conn/socket.h
Labels: topic:refactoring

#4142 add mutt_time_now()
  mbox/mbox.c
  mutt/date.c
  mutt/date.h
  mutt_mailbox.c
Labels: topic:refactoring
