Repository neomutt/neomutt, pull requests merged in 2023-09, with the labels that each got.

#4017 remove search globals
  Makefile.autosetup
  alias/dlg_alias.c
  alias/dlg_query.c
  alias/functions.c
  alias/gui.h
  globals.h
  index/functions.c
  index/shared_data.c
  index/shared_data.h
  pattern/lib.h
  pattern/pattern.c
  pattern/search_state.c
  pattern/search_state.h
  postpone/dlg_postpone.c
  postpone/functions.c
  postpone/functions.h
Labels: topic:refactoring

#4019 remove OptSearchInvalid global
  globals.c
  globals.h
  index/dlg_index.c
  index/functions.c
  pager/dlg_pager.c
  pattern/pattern.c
  test/pattern/dummy.c
Labels: topic:refactoring

#4034 complete: relax complete/query checks
  alias/complete.c
  browser/complete.c
  complete/helpers.c
  notmuch/complete.c
  pattern/complete.c
Labels: type:bug

#4035 remove global EnvList from mutt/filter.c
  alias/dlg_query.c
  attach/mutt_attach.c
  attach/recvattach.c
  conn/accountcmd.c
  conn/connaccount.c
  external.c
  handler.c
  mixmaster/remailer.c
  mutt/filter.c
  mutt/filter.h
  muttlib.c
  ncrypt/pgpinvoke.c
  ncrypt/smime.c
  pager/message.c
  parse/extract.c
  pattern/compile.c
  send/sendlib.c
  test/filter/filter_create.c
  test/filter/filter_create_fd.c
Labels: topic:refactoring

#4037 Refactor the Message Window Usage
  attach/recvattach.c
  conn/dlg_verifycert.c
  enter/wdata.h
  enter/window.c
  external.c
  flags.c
  gui/curs_lib.c
  gui/msgcont.c
  gui/msgcont.h
  gui/msgwin.c
  gui/msgwin.h
  gui/msgwin_wdata.c
  gui/msgwin_wdata.h
  gui/mutt_window.c
  gui/mutt_window.h
  gui/rootwin.c
  index/dlg_index.c
  index/functions.c
  keymap.c
  main.c
  menu/observer.c
  menu/tagging.c
  mutt_logging.c
  mutt_mailbox.c
  muttlib.c
  pager/dlg_pager.c
  question/question.c
  recvcmd.c
Labels: topic:refactoring, type:enhancement, topic:design

#4038 Add Help to Quad/Yes/No Questions
  attach/functions.c
  attach/recvattach.c
  compose/functions.c
  external.c
  imap/imap.c
  imap/message.c
  index/functions.c
  mutt/string.c
  mutt/string2.h
  muttlib.c
  mx.c
  ncrypt/crypt.c
  ncrypt/crypt_gpgme.c
  ncrypt/pgp.c
  nntp/nntp.c
  pager/message.c
  pop/lib.c
  pop/pop.c
  question/lib.h
  question/question.c
  recvcmd.c
  send/send.c
  send/smtp.c
  test/Makefile.autosetup
  test/main.c
  test/string/mutt_str_hyphenate.c
Labels: type:enhancement

#4039 refactor cursor positioning
  enter/wdata.h
  enter/window.c
  flags.c
  gui/curs_lib.c
  gui/msgwin.c
  gui/msgwin_wdata.h
  gui/mutt_window.c
  gui/mutt_window.h
  keymap.c
  question/question.c
Labels: topic:refactoring, topic:design

#4040 explicitly set the focus
  alias/dlg_alias.c
  alias/dlg_query.c
  attach/dlg_attach.c
  autocrypt/dlg_autocrypt.c
  browser/dlg_browser.c
  compose/dlg_compose.c
  conn/dlg_verifycert.c
  gui/dialog.c
  gui/dialog.h
  gui/mutt_window.c
  gui/simple.c
  history/dlg_history.c
  index/dlg_index.c
  index/ipanel.c
  menu/menu.c
  mixmaster/dlg_mixmaster.c
  ncrypt/dlg_gpgme.c
  ncrypt/dlg_pgp.c
  ncrypt/dlg_smime.c
  pager/dlg_pager.c
  pattern/dlg_pattern.c
  postpone/dlg_postpone.c
Labels: topic:refactoring

#4036 eliminate global OptAttachMsg
  attach/dlg_attach.c
  attach/functions.c
  attach/private_data.h
  attach/recvattach.h
  compose/functions.c
  globals.c
  globals.h
  index/dlg_index.c
  index/functions.c
  index/private_data.h
  index/shared_data.h
  mutt_config.c
  pager/dlg_pager.c
  pager/functions.c
  status.c
Labels: topic:refactoring

#4044 disconnect emails from threads
  mview.c
Labels: bug:crash

#4046 color_directcolor: Also set the default/initial value on startup
  init.c
Labels: type:bug

#4051 openssl: continue on signal
  conn/openssl.c
Labels: type:bug
