Repository neomutt/neomutt, pull requests merged in 2023-11, with the labels that each got.

#4098 build: use fallthrough attribute
  attach/dlg_attach.c
  attach/recvattach.c
  auto.def
  autocrypt/gpgme.c
  browser/sort.c
  docs/makedoc.c
  enriched.c
  hdrline.c
  imap/message.c
  imap/util.c
  main.c
  mutt/lib.h
  mutt_mailbox.c
  mutt_signal.c
  ncrypt/pgppacket.c
  ncrypt/smime.c
  pattern/pattern.c
  send/send.c
  sidebar/sort.c
  status.c
Labels: topic:build-process

#4097 config: add DT_ON_STARTUP
  config/bool.c
  config/enum.c
  config/long.c
  config/mbtable.c
  config/mbtable.h
  config/number.c
  config/path.c
  config/quad.c
  config/regex.c
  config/regex2.h
  config/set.h
  config/slist.c
  config/sort.c
  config/string.c
  config/types.h
  maildir/config.c
  mutt_config.c
  ncrypt/config.c
  test/config/bool.c
  test/config/enum.c
  test/config/long.c
  test/config/mbtable.c
  test/config/number.c
  test/config/path.c
  test/config/quad.c
  test/config/regex.c
  test/config/slist.c
  test/config/sort.c
  test/config/string.c
Labels: topic:refactoring, type:enhancement

#4096 hcache: fix key handling
  hcache/hcache.c
  maildir/maildir.c
Labels: type:bug

#4101 version: drop default features
  version.c
Labels: type:discuss

#4104 change mutt_default_save() and addr_hook() to take a buffer
  attach/recvattach.c
  external.c
  hook.c
  hook.h
  muttlib.c
  mx.c
Labels: topic:refactoring

#4105 use buffer pool in tests
  test/base64/mutt_b64_buffer_decode.c
  test/base64/mutt_b64_buffer_encode.c
  test/buffer/buf_add_printf.c
  test/buffer/buf_addch.c
  test/buffer/buf_addstr.c
  test/buffer/buf_addstr_n.c
  test/buffer/buf_concat_path.c
  test/buffer/buf_concatn_path.c
  test/buffer/buf_copy.c
  test/buffer/buf_fix_dptr.c
  test/buffer/buf_is_empty.c
  test/buffer/buf_len.c
  test/buffer/buf_printf.c
  test/buffer/buf_reset.c
  test/buffer/buf_strcpy.c
  test/buffer/buf_strcpy_n.c
  test/buffer/buf_strdup.c
  test/buffer/buf_substrcpy.c
  test/charset/mutt_ch_lookup_add.c
  test/config/dump.c
  test/core/buf_mktemp_full.c
  test/date/mutt_date_make_date.c
  test/file/buf_file_expand_fmt_quote.c
  test/file/buf_quote_filename.c
  test/file/mutt_file_expand_fmt.c
  test/file/mutt_file_resolve_symlink.c
  test/file/mutt_file_sanitize_regex.c
  test/group/mutt_grouplist_add_regex.c
  test/gui/reflow.c
  test/parse/parse_rc.c
  test/path/mutt_path_getcwd.c
  test/pattern/comp.c
  test/regex/mutt_regex_match.c
  test/regex/mutt_regex_new.c
  test/regex/mutt_regexlist_add.c
  test/regex/mutt_replacelist_add.c
  test/url/url_tobuffer.c
Labels: topic:refactoring

#4099 Spanish translation finished, fuzzy words and changed
  po/es.po
Labels: topic:translation

#4106 switch some buffers to use the buffer pool
  browser/functions.c
  color/command.c
  complete/helpers.c
  config/dump.c
  config/set.c
  handler.c
  hcache/hcache.c
  key/dump.c
  main.c
  parse/set.c
Labels: topic:refactoring

#4109 Improve the Progress Bar
  external.c
  imap/message.c
  index/functions.c
  maildir/maildir.c
  mbox/mbox.c
  mh/mh.c
  nntp/nntp.c
  notmuch/notmuch.c
  pattern/pattern.c
  po/bg.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/et.po
  po/eu.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/hu.po
  po/id.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sk.po
  po/sr.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
  pop/lib.c
  pop/pop.c
  progress/lib.h
  progress/progress.c
  progress/window.c
  progress/window.h
  send/smtp.c
Labels: topic:refactoring, type:enhancement

#4115 create HelpBar after colours
  main.c
Labels: type:bug

#4117 remove MxOps::path_parent() and mutt_path_parent()
  compmbox/compress.c
  core/mxapi.h
  imap/imap.c
  maildir/maildir.c
  mbox/mbox.c
  mh/mh.c
  mutt/path.c
  mutt/path.h
  mx.c
  mx.h
  nntp/nntp.c
  notmuch/notmuch.c
  pop/pop.c
  test/Makefile.autosetup
  test/main.c
  test/path/mutt_path_parent.c
Labels: topic:refactoring
