Repository neomutt/neomutt, pull requests merged in 2023-06, with the labels that each got.

#3879 refactor mx_alloc_memory()
  core/mailbox.h
  imap/imap.c
  imap/message.c
  maildir/shared.c
  mbox/mbox.c
  mx.c
  mx.h
  nntp/nntp.c
  notmuch/notmuch.c
  pop/pop.c
Labels: topic:refactoring, type:bug

#3880 logging: increase max length of lines
  mutt/logging.c
  mutt/logging2.h
  mutt_logging.c
Labels: type:bug

#3882 simplify make_reference_headers()
  send/send.c
Labels: topic:refactoring

#3881 imap: rename config imap_keepalive
  attach/mutt_attach.c
  docs/config.c
  imap/config.c
  imap/imap.c
  imap/lib.h
  imap/util.c
  keymap.c
  system.c
Labels: topic:config-file

#3885 Don't create empty buffers for Address mailbox/personal parts
  address/address.c
  hcache/serialize.c
Labels: type:bug

#3889 expandos: use `%<...>` conditionals
  browser/config.c
  docs/config.c
  docs/manual.xml.head
  docs/neomuttrc.man.head
  mutt_config.c
Labels: topic:config-file

#3892 hcache: cache store/comp ops
  compress/compress.c
  compress/lib.h
  compress/lz4.c
  compress/zlib.c
  compress/zstd.c
  hcache/hcache.c
  hcache/lib.h
  imap/mdata.c
  imap/message.c
  imap/util.c
  maildir/maildir.c
  maildir/mh.c
  nntp/newsrc.c
  nntp/nntp.c
  notmuch/notmuch.c
  pop/pop.c
  store/bdb.c
  store/gdbm.c
  store/kc.c
  store/lib.h
  store/lmdb.c
  store/qdbm.c
  store/rocksdb.c
  store/store.c
  store/tc.c
  store/tdb.c
  test/compress/common.c
  test/compress/lz4.c
  test/compress/zlib.c
  test/compress/zstd.c
  test/store/bdb.c
  test/store/common.c
  test/store/gdbm.c
  test/store/kc.c
  test/store/lmdb.c
  test/store/qdbm.c
  test/store/rocksdb.c
  test/store/store.c
  test/store/tc.c
  test/store/tdb.c
Labels: topic:refactoring, type:bug

#3896 test for, and fix, logging problems
  mutt/logging.c
  mutt/logging2.h
  mutt_logging.c
  mutt_logging.h
Labels: topic:build-process, type:bug

#3897 Fix for <sync-mailbox> "Unable to write" when email (in a Maildir) wa…
  maildir/maildir.c
Labels: type:bug, topic:maildir

#3900 Treat complete-query as complete where it makes sense
  enter/functions.c
Labels: type:enhancement

#3906 MxOps path_canon() and path_pretty() take a Buffer
  compmbox/compress.c
  core/mxapi.h
  imap/imap.c
  imap/lib.h
  maildir/maildir.c
  maildir/mh.c
  mbox/mbox.c
  mx.c
  mx.h
  nntp/nntp.c
  notmuch/notmuch.c
  pop/pop.c
Labels: topic:refactoring
