Repository neomutt/neomutt, pull requests merged in 2024-12, with the labels that each got.

#4437 show message preview in compose view
  Makefile.autosetup
  compose/attach.c
  compose/config.c
  compose/dlg_compose.c
  compose/functions.c
  compose/lib.h
  compose/preview.c
  compose/private.h
  compose/shared_data.h
  docs/config.c
  docs/manual.xml.head
  gui/mutt_window.h
  gui/opcodes.h
Labels: type:enhancement

#4467 fix: Bug with wrong fingerprints in certificate_file
  conn/gnutls.c
Labels: type:bug

#4470 fix postponed sorting assertion failure
  mutt_thread.c
Labels: bug:crash, has:backtrace

#4475 edit_headers: cleanup temporary file on error
  mutt_header.c
Labels: bug:confirmed

#4472 fix: `save_attachment_open()` when overwriting
  attach/mutt_attach.c
Labels: type:bug

#4480 fix memory leak in compose message preview (fixes #4478)
  compose/preview.c
Labels: bug:leak

#4477 fix crash in folder-hook
  main.c
Labels: bug:crash

#4485 lua: fix lua_mutt_call()
  mutt_lua.c
Labels: topic:lua-scripting, type:bug

#4481 Simplify mutt_file_fopen
  alias/alias.c
  attach/mutt_attach.c
  attach/mutt_attach.h
  attach/recvattach.c
  compmbox/compress.c
  compose/functions.c
  history/history.c
  mutt/file.c
  mutt/file.h
  muttlib.c
Labels: topic:refactoring
