Repository neomutt/neomutt, pull requests merged in 2024-10, with the labels that each got.

#4391 Don't return the result of `realpath` on failure
  commands.c
  mutt/path.c
  test/path/mutt_path_to_absolute.c
Labels: bug:confirmed

#4399 fix duplicate save-hook
  hook.c
Labels: type:bug

#4409 Use FreeBSD 14.1 in Cirrus CI
  .cirrus.yml
Labels: topic:automation

#4404 browser: fix enter-quit-enter
  editor/window.c
Labels: type:bug

#4403 tags: fix conditionals
  mutt_config.c
Labels: type:bug

#4407 config: warn about deprecated variables
  parse/set.c
Labels: bug:crash

#4405 pager: fix repaint
  pager/ppanel.c
Labels: type:bug

#4300 ncrypt/crypt.c: Read the protected Message-ID
  ncrypt/crypt.c
Labels: type:enhancement
