Repository neomutt/neomutt, pull requests merged in 2024-02, with the labels that each got.

#4186 buffer: make_entry()
  alias/dlg_alias.c
  alias/dlg_query.c
  attach/dlg_attach.c
  autocrypt/dlg_autocrypt.c
  browser/dlg_browser.c
  compmbox/compress.c
  compose/attach.c
  conn/dlg_verifycert.c
  copy.c
  gui/format.c
  gui/format.h
  handler.c
  hdrline.c
  hdrline.h
  history/dlg_history.c
  hook.c
  index/dlg_index.c
  index/ibar.c
  index/lib.h
  menu/draw.c
  menu/lib.h
  menu/menu.c
  mixmaster/win_hosts.c
  mutt/state.h
  ncrypt/dlg_gpgme.c
  ncrypt/dlg_pgp.c
  ncrypt/dlg_smime.c
  ncrypt/pgpinvoke.c
  ncrypt/smime.c
  pager/dlg_pager.c
  pager/message.c
  pager/pbar.c
  pattern/dlg_pattern.c
  postpone/dlg_postpone.c
  recvcmd.c
  send/send.c
  sidebar/window.c
  status.c
  status.h
Labels: topic:refactoring

#4189 Fix off-by-one error in %b with notmuch
  hdrline.c
Labels: type:bug, topic:notmuch

#4190 Zero-out mailbox counters on delete
  core/mailbox.c
Labels: bug:crash
