Repository neomutt/neomutt, pull requests merged in 2024-04, with the labels that each got.

#4232 expando: fix attach search
  expando/expando.c
  menu/menu.c
Labels: type:bug

#4245 build: enable CodeQL for python
  .github/workflows/codeql.yml
Labels: topic:build-process

#4253 Remove spurious comment
  address/address.c
Labels: docs:code

#4264 mutt: fix copyright boilerplate in base64.h and filter.h
  mutt/base64.h
  mutt/filter.h
Labels: docs:code

#4261 expando: fixes
  Makefile.autosetup
  alias/dlg_alias.c
  alias/dlg_query.c
  attach/dlg_attach.c
  autocrypt/dlg_autocrypt.c
  browser/dlg_browser.c
  compose/attach.c
  compose/cbar.c
  expando/filter.c
  expando/filter.h
  expando/helpers.c
  expando/helpers.h
  expando/lib.h
  expando/node.c
  expando/node.h
  expando/node_container.c
  expando/node_expando.c
  expando/parse.c
  hdrline.c
  history/dlg_history.c
  mixmaster/win_hosts.c
  ncrypt/dlg_gpgme.c
  ncrypt/dlg_pgp.c
  nntp/newsrc.c
  pattern/dlg_pattern.c
  send/send.c
  send/sendmail.c
  sidebar/window.c
  status.c
  test/Makefile.autosetup
  test/expando/filter.c
  test/expando/format.c
  test/expando/helpers.c
  test/expando/node.c
  test/expando/node_container.c
  test/expando/node_expando.c
  test/expando/node_padding.c
  test/main.c
Labels: type:enhancement, type:bug

#4263 fix: cache naming
  bcache/bcache.c
  hcache/hcache.c
  nntp/newsrc.c
Labels: type:bug, topic:hcache

#4272 expando: allow newline
  expando/format.c
Labels: type:bug

#4273 guard truecolor function in tests
  test/color/attr.c
Labels: topic:build-process

#4275 use homebrew in macOS build
  .github/workflows/macos.yml
Labels: topic:build-process

#4280 Update autosetup (bundled jim)
  autosetup/jimsh0.c
Labels: topic:build-process

#4281 Update acutest to the latest upstream commit
  test/acutest.h
Labels: topic:build-process, topic:testing
