Repository neomutt/neomutt, pull requests merged in 2024-03, with the labels that each got.

#4212 test: remove unnecessary setting of TZ var
  test/expando/node_conddate.c
Labels: topic:testing

#4211 config: implement expando plus-equals
  expando/config_type.c
Labels: type:enhancement, type:bug

#4215 mbox: fix sorting for mbox_resync()
  mbox/mbox.c
  sort.c
  sort.h
Labels: type:bug

#4219 expando: don't render the condition node
  expando/config_type.c
  expando/expando.c
  expando/helpers.c
  expando/node_condition.c
  test/config/string.c
  test/expando/config.c
  test/expando/helpers.c
Labels: type:bug
