Repository neomutt/neomutt, pull requests merged in 2024-11, with the labels that each got.

#4423 expando: fix and refactor
  browser/config.c
  expando/definition.h
  expando/expando.c
  expando/format.c
  expando/helpers.c
  expando/helpers.h
  expando/node_condbool.c
  expando/node_condbool.h
  expando/node_conddate.c
  expando/node_condition.c
  expando/node_condition.h
  expando/node_container.c
  expando/node_expando.c
  expando/node_expando.h
  expando/node_padding.c
  expando/node_padding.h
  expando/node_text.c
  expando/node_text.h
  expando/parse.c
  expando/parse.h
  mutt_config.c
  ncrypt/config.c
  test/Makefile.autosetup
  test/expando/colors_render.c
  test/expando/common.c
  test/expando/common.h
  test/expando/complex_if_else.c
  test/expando/date_render.c
  test/expando/empty.c
  test/expando/expando.c
  test/expando/format.c
  test/expando/format_number.c
  test/expando/formatted_expando.c
  test/expando/helpers.c
  test/expando/new_if_else.c
  test/expando/node_condbool.c
  test/expando/node_conddate.c
  test/expando/node_condition_parse.c
  test/expando/node_container.c
  test/expando/node_expando.c
  test/expando/node_padding.c
  test/expando/node_text_parse.c
  test/expando/old_if_else.c
  test/expando/padding.c
  test/expando/parse.c
  test/expando/parse_short_name.c
  test/expando/percent_sign_text.c
  test/expando/serial.c
  test/main.c
Labels: topic:refactoring, type:bug

#4432 fix unmacro docs
  docs/manual.xml.head
Labels: docs:manual

#4433 compose: fix redraw on attachment
  compose/cbar.c
  compose/dlg_compose.c
Labels: type:bug

#4438 autocrypt: fix copy_normalize_addr()
  autocrypt/db.c
Labels: type:bug

#4440 remove unused mailbox param from mutt_count_body_parts
  attach/attachments.c
  attach/attachments.h
  hdrline.c
  pattern/exec.c
Labels: topic:refactoring

#4449 add mutt_window_swap()
  gui/mutt_window.c
  gui/mutt_window.h
  test/Makefile.autosetup
  test/gui/swap.c
  test/main.c
Labels: type:enhancement
