Repository neomutt/neomutt, pull requests merged in 2024-05, with the labels that each got.

#4149 Respect umask when saving attachments
  attach/mutt_attach.c
  core/neomutt.c
  core/neomutt.h
  docs/manual.xml.head
  maildir/message.c
  main.c
  mh/shared.c
  mutt/file.c
  mutt/file.h
  send/sendlib.c
  test/file/mutt_file_open.c
Labels: type:enhancement

#4221 ncrypt/crypt_gpgme.c: Show encryption information
  docs/config.c
  docs/manual.xml.head
  ncrypt/config.c
  ncrypt/crypt_gpgme.c
Labels: type:discuss, topic:security, type:enhancement

#4256 $crypt_protected_headers_write: Change default to 'yes'
  docs/config.c
  docs/manual.xml.head
  ncrypt/config.c
Labels: bug:upstream, topic:security, type:bug

#4249 Cryptoweed; Add `$crypt_protected_headers_weed`
  docs/config.c
  ncrypt/config.c
  ncrypt/crypt.c
Labels: topic:security, type:enhancement

#4291 Revert "ncrypt/crypt.c: Protect Date"
  ncrypt/crypt.c
Labels: type:bug

#4304 Spanish translation finished
  po/es.po
Labels: topic:translation

#4307 build: require C11
  INSTALL.md
  auto.def
Labels: topic:build-process

#4305 remove mutt_expand_path() and mutt_expand_path_regex()
  alias/alias.c
  browser/functions.c
  commands.c
  imap/imap.c
  imap/lib.h
  mutt_lua.c
  muttlib.c
  muttlib.h
  nntp/newsrc.c
  send/sendlib.c
  test/pattern/dummy.c
Labels: topic:refactoring

#4308 fix -Wdouble-promotion warnings
  conn/zstrm.c
  send/sendlib.c
Labels: topic:refactoring

#4310 scanf: initialise out-vars
  history/history.c
  imap/message.c
  mutt/date.c
  nntp/newsrc.c
  nntp/nntp.c
  pop/pop.c
Labels: topic:build-process

#4312 Allow opening the header cache in non-O_CREAT mode
  hcache/hcache.c
  hcache/lib.h
  imap/imap.c
  imap/mdata.c
  imap/message.c
  imap/private.h
  imap/util.c
  maildir/hcache.c
  mh/mh.c
  nntp/newsrc.c
  notmuch/notmuch.c
  pop/pop.c
  store/bdb.c
  store/gdbm.c
  store/kc.c
  store/lib.h
  store/lmdb.c
  store/qdbm.c
  store/rocksdb.c
  store/tc.c
  store/tdb.c
  test/store/bdb.c
  test/store/common.c
  test/store/gdbm.c
  test/store/kc.c
  test/store/lmdb.c
  test/store/qdbm.c
  test/store/rocksdb.c
  test/store/tc.c
  test/store/tdb.c
Labels: type:enhancement, topic:hcache

#3945 conn: do not prompt for username with client certificate
  conn/gnutls.c
  conn/openssl.c
Labels: type:bug
