Repository neomutt/neomutt, pull requests merged in 2025-03, with the labels that each got.

#4582 pager: fix lost NT_PAGER notifications
  pager/dlg_pager.c
  pager/pager.c
Labels: type:bug

#4589 Remove unused import from mutt_oauth2.py
  contrib/oauth2/mutt_oauth2.py
Labels: topic:refactoring

#4591 pager: fix refresh on <top>
  pager/dlg_pager.c
  pager/functions.c
  pager/pager.c
Labels: type:bug

#4593 browser: tag select rather than descend
  browser/functions.c
Labels: type:enhancement

#4596 query: allow <>s around email addresses
  alias/dlg_query.c
Labels: type:discuss, type:bug

#4595 notmuch: check for parse failure
  notmuch/notmuch.c
Labels: type:bug, topic:notmuch
