Repository neomutt/neomutt, pull requests merged in 2025-04, with the labels that each got.

#4600 main: don't stop if /var/spool/mail is missing
  main.c
Labels: type:bug

#4602 color: fix quoted maths
  color/quoted.c
Labels: type:bug

#4604 Don't consider "weed" when writing an email to file
  copy.c
Labels: type:bug

#4605 help: fix leaks
  help.c
Labels: bug:leak

#4612 imap: check for incomplete Mailboxes on sync
  imap/imap.c
Labels: bug:crash
