Repository neomutt/neomutt, pull requests merged in 2025-01, with the labels that each got.

#4490 notmuch: refresh the Email if the filename changes
  notmuch/notmuch.c
Labels: type:bug, topic:notmuch

#4492 colour refactoring
  color/color.h
  color/command.c
  color/dump.c
  color/quoted.c
  color/quoted.h
  color/regex.c
  color/simple2.h
  debug/notify.c
  docs/manual.xml.head
  docs/neomuttrc.man.head
  pager/display.c
  test/color/color_dump.c
Labels: topic:refactoring

#4538 move real_name init
  init.c
Labels: type:bug

#4545 Allow nested ARRAY_FOREACH()
  alias/dlg_alias.c
  alias/dlg_query.c
  alias/functions.c
  alias/sort.c
  autocrypt/dlg_autocrypt.c
  browser/dlg_browser.c
  expando/node_padding.c
  maildir/mailbox.c
  mh/mh.c
  mutt/array.h
  pattern/pattern.c
  send/send.c
  sidebar/functions.c
  sidebar/sidebar.c
  sidebar/window.c
  test/array/mutt_array_api.c
Labels: type:enhancement

#4546 Respect Ignore when modifying an email's headers
  copy.c
Labels: type:bug

#4536 expand tabs to spaces in compose preview (fixes #4534)
  compose/preview.c
  mutt/string.c
  mutt/string2.h
  test/Makefile.autosetup
  test/main.c
  test/string/mutt_str_expand_tabs.c
Labels: type:bug

#4543 debug: Chain old SEGV Handler
  mutt/signal.c
  mutt/signal2.h
  mutt_signal.c
Labels: type:enhancement

#4537 fix dumping of initial values
  config/dump.c
  config/set.c
  init.c
Labels: type:bug

#4549 fix refresh on toggle hide_thread_subject
  index/index.c
Labels: type:bug

#4550 buffer: fix seek
  mutt/buffer.c
Labels: type:bug

#4551 add comma to single <complete-query> match
  alias/dlg_query.c
Labels: type:bug

#4552 Deprecate some configure options that aren't used anymore
  auto.def
Labels: topic:refactoring, topic:build-process

#4557 config: drop ConfigSet from API functions
  address/config_type.c
  config/bool.c
  config/charset.c
  config/charset.h
  config/enum.c
  config/long.c
  config/mbtable.c
  config/myvar.c
  config/number.c
  config/path.c
  config/quad.c
  config/regex.c
  config/set.c
  config/set.h
  config/slist.c
  config/sort.c
  config/string.c
  expando/config_type.c
  hcache/config.c
  imap/config.c
  maildir/config.c
  mutt_config.c
  mutt_logging.c
  mutt_logging.h
  mutt_thread.c
  mutt_thread.h
  notmuch/config.c
  pop/config.c
  send/config.c
  test/config/common.c
  test/config/common.h
  test/config/set.c
  test/expando/config.c
Labels: topic:refactoring
